- BasisProject.cmake
To avoid confusion with the tagged release version, change version number of master branch after first bugfix commit after the release.
> cmake: Change version to 1.0.1 for next release

- Applications/CMakeLists.txt
- Modules/ImageIO/src/CMakeLists.txt
Even though CMake should add the transitive link dependencies by itself, Paul reported he had to list them explicitly on OS X 10.11 (El Capitan) with CMake 2.8.12.
> fix: CMake for some reason not pulling in the transitive dependencies

- Modules/PointSet/src/mirtkImplicitSurfaceUtils.cc
The image was incorrectly copied from the input distance map to the VTK image. The pointer used to iterate over the input image was incremented before assignment instead of afterwards.
> fix: extract-surface produces surface with slight offset

- Modules/Image/src/mirtkImageToImage.cc
- Modules/Image/src/mirtkResampling.cc
The ```ImageToImage::Finalize``` function only copies the image content from the temporary output image, but not the image attributes. Secondly, it is not necessary to allocate the output image in the base class in case of ```Resampling::Initialize``` as it will be re-allocated by this function then again.
> Fix resampling filter

- Applications/calculate-distance-map.cc
The verbose output was incorrectly formatted. The more important issue was missing handling of the standard options and to display an error when the option is unknown.
> fix: Verbose output of calculate-distance-map and option parsing

- Modules/PointSet/BasisProject.cmake
- Modules/PointSet/include/mirtkEdgeTable.h
- Modules/PointSet/src/mirtkEdgeTable.cc
- Modules/PointSet/test/CMakeLists.txt
- Modules/PointSet/test/testEdgeTable.cc
The ```EdgeTable::GetNextEdge``` function would not skip "empty" columns where there is no element for which the row index is less (or equal) than the column index. This resulted in the first edge in that column to be visited twice and the edge ID not matching the entry in the sparse matrix (edge table).
> Fix EdgeTable::GetNextEdge

- Applications/extract-pointset-surface.cc
- Applications/smooth-surface.cc
- Modules/Common/include/mirtkCommon.h
- Modules/Common/include/mirtkMath.h
- Modules/Common/src/CMakeLists.txt
- Modules/Common/src/mirtkMath.cc
- Modules/Numerics/src/mirtkArith.cc
- Modules/Numerics/src/mirtkMatrix3x3.cc
- Modules/Numerics/src/mirtkPointSamples.cc
- Modules/Numerics/src/mirtkScalarGaussian.cc
- Modules/Numerics/src/mirtkSinc.cc
- Modules/PointSet/include/mirtkImplicitSurfaceUtils.h
- Modules/PointSet/src/mirtkPolyDataCurvature.cc
- Modules/PointSet/src/mirtkPolyDataRemeshing.cc
- Modules/PointSet/src/mirtkSurfaceCollisions.cc
- Modules/Registration/src/mirtkCurrentsDistance.cc
- Modules/Transformation/src/mirtkAffineTransformation.cc
- Modules/Transformation/src/mirtkInverseAffineTransformation.cc
- Modules/Transformation/src/mirtkRigidTransformation.cc
Related to issue #52. Solves issue with ```cmath``` header file include only after ```_USE_MATH_DEFINES``` (see [this SO thread](http://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio) for details on the dilemma). The ```_USE_MATH_DEFINES``` was missing before and thus the build errors with MSVC.
> enh: Define and use own constants for \pi

- Applications/remesh.cc
- Modules/PointSet/include/mirtkEdgeTable.h
- Modules/PointSet/include/mirtkPolyDataRemeshing.h
- Modules/PointSet/src/mirtkPolyDataRemeshing.cc
The surface remeshing filter would not always preserve the topology of the input surface mesh. Also, the melting operations were not performed in an order that results in more regular output meshes.
> Fix surface remeshing filter

- Applications/close-image.cc
- Applications/convert-image.cc
- Applications/dilate-image.cc
- Applications/erode-image.cc
- Modules/Image/include/mirtkBaseImage.h
- Modules/Image/src/mirtkBaseImage.cc
- Modules/Image/src/mirtkGenericImage.cc
- Modules/Image/src/mirtkVoxel.cc
- Modules/ImageIO/src/mirtkNiftiImageReader.cc
- Modules/ImageIO/src/mirtkNiftiImageWriter.cc
The morphological image commands were limited to only common voxel types. Now they can process any type of images. Moreover, the convert-image command now also has the options ```-binary```, ```-real```...
> Morphological commands should be able to process any type of image

- Modules/Common/include/mirtkCommon.h
- Modules/Common/include/mirtkPriorityQueue.h
- Modules/Common/src/CMakeLists.txt
- Modules/Image/include/mirtkBinaryVoxelFunction.h
Not actually used, but add it anyway for sake of "completeness".
> Add mirtk::PriorityQueue type alias for std::priority_queue

- Applications/calculate.cc
- Modules/Image/include/mirtkDataFunctions.h
Fixes the result of a division by zero, which is NaN in any case even when for IEEE floating point numbers the result is +/- Inf. Also fixes the ```-mask``` operation to support the value ```NaN``` which can be used to mask such undefined devision results. Adds further a new ```-div-with-zero``` option to the calculate command for the common use case of dividing one image by another and replacing resulting NaNs by zero.
> Fix calculate divide by zero

- Applications/smooth-image.cc
Thanks @amakropoulos. Relates to one of the commits of PR #70.
> fix: switch case missing break in smooth-image [Applications]

- Modules/Image/include/mirtkHashImage.h
- Modules/Image/include/mirtkHashImage.hxx
- Modules/Image/src/CMakeLists.txt
- Modules/Image/src/mirtkHashImage.cc
This class is an image implementation based on hashmap (unordered_map).
Instead of storing the data in a continuous array, only the non-empty voxels are stored.
By default the voxels with 0 value are the empty voxels.
The empty_value specifies the value that defines the empty voxels.
> add hash image

- CMake/Settings.cmake
Alternative fix for #76 where cache entry properties are only modified when the CMAKE_BUILD_TYPE related cache entries exist.
> #52 Set CMAKE_BUILD_TYPE STRINGS only when cache entry exists

- Modules/Registration/src/mirtkNormalizedIntensityCrossCorrelation.cc
There was a ```name + 19``` instead of ```name + 17``` spotted by @stefanpsz. Introduced constants and use of ```strlen``` to avoid these mistakes.
> fix: Parsing of LNCC window size [Registration]

- Modules/Image/include/mirtkBaseImage.h
- Modules/Image/include/mirtkConstImageIterator.h
- Modules/Image/include/mirtkConvolutionFunction.h
- Modules/PointSet/include/mirtkImplicitSurfaceUtils.h
- Modules/PointSet/src/mirtkPolyDataRemeshing.cc
- Add BaseImage::XSize() et al. property getters.
- Add ImplicitSurfaceUtils::SignedDistance functions.
- Add ConvolveForegroundInX et al. voxel functions. Didn't really end up using these because probably the corresponding 3D convolution is no longer separable in this way. These should only be used in a single dimension. What I am saying, use with care, don't just use blindly.
- Make ConstImageIterator::Move useable with pointer types different from VoxelType.
> Various smaller "fixes" and enhancements

- CMake/Modules/MIRTKAddTest.cmake
This should have been part of PR #87 already.
> fix: Use new mirtk_get_target_name also in mirtk_add_test [CMake]

- .dockerignore
- Dockerfile
A Docker image for running MIRTK in an Ubuntu 14.04 container with MIRTK installed in /usr/local can be built using the "docker build" command. An automated Docker image build can further be set up on Docker Hub.
> enh: Add Dockerfile and .dockerignore

- BasisProject.cmake
Version 1.0.1 will be skipped because not only bug fixes have been merged into the develop branch. No need for a separate bug fix release.
> Change version to 1.1.0

- Applications/calculate-surface-spectrum.cc
- Applications/evaluate-distance.cc
- Applications/info.cc
- Applications/offset-surface.cc
- Applications/remesh.cc
- Applications/smooth-surface.cc
- Modules/Common/include/mirtkVtkMath.h
- Modules/Common/src/CMakeLists.txt
- Modules/PointSet/include/mirtkPointSetUtils.h
- Modules/PointSet/include/mirtkTriangle.h
- Modules/PointSet/src/mirtkClosestPointLabel.cc
- Modules/PointSet/src/mirtkEdgeConnectivity.cc
- Modules/PointSet/src/mirtkPolyDataCurvature.cc
- Modules/PointSet/src/mirtkPolyDataRemeshing.cc
- Modules/PointSet/src/mirtkPolyDataSmoothing.cc
- Modules/PointSet/src/mirtkRobustPointMatch.cc
- Modules/PointSet/src/mirtkSurfaceCollisions.cc
- Modules/Registration/src/mirtkCurrentsDistance.cc
This PR fixes the build with VTK 6.0.0 using "macro injection" to fix the ambiguity of ```isnan``` and ```isinf``` in ```vtkMath.h```. Moreover, it updates the Packages submodules where the Deformable package also contains a fix for a bug that was only discovered by chance when building with VTK 6.0.0 because the ```vtkDataArray::GetArrayType``` function was not present in this release yet. But actually the code needed to call ```vtkDataArray::GetDataType``` instead anyway...
With this PR, the MIRTK can be build with the ```libvtk6-dev``` package on Ubuntu 14.04. No need for a custom VTK build.
> Fix build with VTK 6.0.0

- CMake/Basis/CommonTools.cmake
This change does not really affect MIRTK, but I came across this and made the change here anyway. To be pushed upstream.
> enh: Do not add WITH_<Pkg> option when USE_<Pkg> variable set [BASIS]

- CMake/Config/Depends.cmake
- Modules/Common/BasisProject.cmake
- Modules/Image/BasisProject.cmake
- Modules/Numerics/BasisProject.cmake
- Modules/PointSet/BasisProject.cmake
- Modules/Registration/BasisProject.cmake
- Modules/Transformation/BasisProject.cmake
The new basis_find_package function accepts an ordered list of alternative versions to look for. The first found version is used. Closes #45.
> fix: Find VTK 7 as alternative to version 6

- Documentation/contents.rst
- Documentation/help.rst
- Documentation/sidebar.rst
- Change order of "Applications" and "Modules" pages in TOC and side bar such that the list of commands comes next to the "Get Started" guide/
- Rename "Getting Help" to "Get Help".
> Enh: Documentation sidebar changes

- Documentation/help.rst
This PR updates the link of the community support mailing-list for `doc-biomedic-irtk` to the new `mirtk-user`. I also took this opportunity to correct the "Get help" title to something with less of a [double meaning](https://www.mentalhealth.org.uk/your-mental-health/getting-help).
> Update the help section of documentation.

- Applications/convert-dof.cc
This PR contains a few minor fixes and changes of the ```convert-dof``` tool as well. The main fix is the conversion of a transformation to an FSL warp. The transformed point in the source image must be multiplied with the source image voxel size, not the target image voxel size, to convert to mm units. For the conversion to a relative warp, the target voxel size is needed, though.
> Fix conversion of transformation to FSL warp

- Applications/convert-dof.cc
Also, require ```-target``` and ```-source``` when converting to FSL. Result is useless otherwise.
> Enh: Set default convert-dof output format based on extension

- CMake/Modules/mirtkAddLibrary.cmake
- ThirdParty/LBFGS/CMakeLists.txt
- ThirdParty/NiftiCLib/CMakeLists.txt
This allows the installation of both optimised and debug libraries as well as static and shared libraries in the same destination. The use of static libraries is generally not recommended and hence there is currently no option to build both static and shared libraries at the same time. They may be installed to the same directory, however, after build with different CMake configurations.
> Enh: Add postfix to debug libraries and static libraries on Windows

- CMake/Basis/CommonTools.cmake
Change overridden find_package function of CMake BASIS to set ```<Pkg>_<VAR>``` if it is either not defined yet, empty, or ```NOTFOUND``` to the value of ```<PKG>_<VAR>``` when the latter is defined. Do this also when ```<Pkg>_<VAR>``` is already defined (but not set or FALSE).
Fixes #157.
> fix: Set common unset <Pkg>_<VAR> to <PKG>_<VAR> if the latter is defined [BASIS]

- Applications/CMakeLists.txt
> fix: Install mirtk/__init__.py module in Python path of public modules [Applications]

- Modules/Common/src/String.cc
- Modules/Common/test/testString.cc
- Modules/Numerics/test/CMakeLists.txt
- Modules/Numerics/test/testMatrix.cc
- Modules/Numerics/test/testPolynomial.cc
- Modules/Registration/src/NormalizedIntensityCrossCorrelation.cc
- Fix bugs in ```ParameterUnits``` and ```ValueUnits``` functions.
- Fix build configuration of Numerics module tests.
- Remove obsolete LNCC auxiliary function.
> Fix units parsing and tests build

- Modules/Transformation/src/TransformationInverse.cc
Not much of a "fix", just a disabling of warnings.
> fix: MSVC warnins for TransformationInverse.cc Boost includes [Transformation]

- Modules/Common/include/mirtk/System.h
- Modules/Common/src/System.cc
- Modules/IO/src/PointSetIO.cc
Turns out GCC 4.8 does not implement the ```std::put_time``` manipulator yet.
> fix: Build of system information functions with GCC and MSVC [Common]

- Applications/src/CMakeLists.txt
When the Applications module would be built outside the MIRTK source tree, the ```MODULE``` variables are not defined. Instead, the ```MIRTK_<Module>_FOUND``` variables should be used which is intended for use by client projects (which each MIRTK module could potentially be itself).
> fix: Use MIRTK_<Module>_FOUND instead of MODULE_<Module> option of top-level project [Applications]

- CMake/Basis/MatlabTools.cmake
- CMake/Basis/TargetTools.cmake
- CMake/Modules/mirtkAddExecutable.cmake
This is a minor change that helps to keep the top-level build directory cleaner when using the Visual Studio generator on Windows.
> enh: Finalize custom targets immediately [BASIS, CMake]

- Modules/Common/include/mirtk/Math.h
Tried to compile on Ubuntu 16.04. Hit a bug with non-declaration of `isnan` and `isinf`. This patch fixes the error.
> Fix missing using std with isinf and isnan.

- Applications/src/edit-image.cc
Options were not parsed correctly. Use ```PARSE_ARGUMENT``` macro.
> fix: Parsing of command line options of edit-image command [Applications]

- Applications/lib/python/mirtk/subprocess.py.in
> fix: Use 'str' instead of 'basestring' for compatibility with Python 3 [Applications]

- Applications/src/evaluate-similarity.cc
- Modules/Registration/include/mirtk/HistogramImageSimilarity.h
- Modules/Registration/include/mirtk/ImageCovariance.h
- Modules/Registration/include/mirtk/IntensityCorrelationRatioXY.h
- Modules/Registration/include/mirtk/IntensityCorrelationRatioYX.h
- Modules/Registration/include/mirtk/JointImageEntropy.h
- Modules/Registration/include/mirtk/LabelConsistency.h
- Modules/Registration/include/mirtk/MutualImageInformation.h
- Modules/Registration/include/mirtk/NormalizedMutualImageInformation.h
- Modules/Registration/include/mirtk/Registration.h
- Modules/Registration/src/CMakeLists.txt
- Modules/Registration/src/HistogramImageSimilarity.cc
- Modules/Registration/src/ImageCovariance.cc
- Modules/Registration/src/IntensityCorrelationRatioXY.cc
- Modules/Registration/src/IntensityCorrelationRatioYX.cc
- Modules/Registration/src/JointImageEntropy.cc
- Modules/Registration/src/LabelConsistency.cc
- Modules/Registration/src/MutualImageInformation.cc
- Modules/Registration/src/NormalizedMutualImageInformation.cc
This is the base class name used by the IRTK. The previous ProbabilisticImageSimiarity name also lead to some confusion whether this was some other kind of probabilistic similarity measure. The name HistogramImageSimilarity should be less confusing.
> enh: Rename ProbabilisticImageSimilarity to HistogramImageSimilarity [Registration]

- Modules/Common/config/Settings.cmake
- Modules/Common/config/config.h.in
- Modules/Common/include/mirtk/Memory.h
- Modules/Common/src/Cifstream.cc
- Modules/Common/src/Cofstream.cc
- Modules/Common/src/Memory.cc
- Modules/Numerics/config/Settings.cmake
- Modules/Numerics/config/config.h.in
- Modules/Numerics/include/mirtk/Matrix.h
- Modules/Numerics/include/mirtk/Vector.h
- Modules/Numerics/src/Matrix.cc
- Modules/Numerics/src/Vector.cc
- Modules/Numerics/test/CMakeLists.txt
- Modules/Numerics/test/testMatrix.cc
- Modules/Numerics/test/testVector.cc
- Modules/Transformation/src/Transformation.cc
Check endianness of machine at runtime and swap bytes if necessary to store them in big endianness order. Unit tests for vector/matrix IO functions to be added to this PR soon.
Closes #217.
> fix: Always store binary data in big-endian order

- Modules/IO/BasisProject.cmake
- Modules/Numerics/BasisProject.cmake
Not very important for shared library builds, but would probably fail a static linking of the libraries. In any case, CMake is warning about it.
> fix: CMake warning about missing TBB::tbb import target [Numerics,IO]

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/240)
> fix: Remove non-working Docker image layers badge from README

- .travis.yml
Remove `tests=off` environment variable from `.travis.yml`. Instead, set this variable in the [Settings](https://travis-ci.org/BioMedIA/MIRTK/settings).
> enh: Use also Clang compiler for Travis CI builds

- .gitmodules
- BasisProject.cmake
- Documentation/modules.rst
- Documentation/modules/_descriptions/mapping.rst
- Documentation/modules/_descriptions/volumetricmapping.rst
- Documentation/modules/mapping.rst
- Documentation/modules/volumetricmapping.rst
The `Mapping` module will be extended to also includes methods for computing surface maps. Hence, a more general module name is needed. It's also nicer to have a single substantive as module name similar to all other modules...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/266)
> enh: Rename module [VolumetricMapping -> Mapping]

- ChangeLog.txt
> doc: Fix reference to renamed VolumetricMapping module [ChangeLog]

- Applications/src/convert-mris.py
Modify `convert-mris` script so it works either with VTK 5 or VTK 6/7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/271)
> fix: Make convert-mris work with both VTK 5 and >=6 [Applications]

- Applications/src/info.cc
- Modules/PointSet/include/mirtk/PointSetUtils.h
- Modules/PointSet/src/PointSetUtils.cc
Fix computation of genus for non-closed surface meshes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/273)
> fix: Surface genus computation, add auxiliary functions to get surface boundary [PointSet, Applications]

- Modules/PointSet/src/PointSetUtils.cc
> fix: Remove unused include of vtkCellIterator which is further not available in VTK 6.0 [PointSet]

- Modules/Common/include/mirtk/String.h
- Modules/Common/src/String.cc
Helper function to convert (upper) camel case string (e.g., "ArealDistortion") to MIRTK style (see register command configuration file) parameter name (e.g., "Areal distortion").
> enh: Add CamelCaseToPrettyParameterName function [Common]

- Modules/Common/include/mirtk/Numeric.h
- Modules/Common/src/CMakeLists.txt
MIRTK header file `Numeric.h` which includes STL's `numeric` header and imports used functions into the `mirtk` namespace, plus additional basic MIRTK helper functions.
> enh: Add header which imports used STL's numeric functions into mirtk namespace [Common]

- Modules/PointSet/include/mirtk/PolyDataCurvature.h
- Modules/PointSet/src/PolyDataCurvature.cc
Just for convenience to be able to select the type of curvature measures to compute already upon construction instead of a separate setter call.
> enh: Add constructor argument to PolyDataCurvature filter [PointSet]

- Modules/PointSet/include/mirtk/PointSetUtils.h
- Modules/PointSet/include/mirtk/Triangle.h
Also adds missing `inline` declarations to functions defined in `Triangle.h` header file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/308)
> enh: Move Cotangent function to Triangle class

- Modules/PointSet/include/mirtk/BoundarySegment.h
- Modules/PointSet/include/mirtk/PointSetUtils.h
- Modules/PointSet/include/mirtk/SurfaceBoundary.h
- Modules/PointSet/src/BoundarySegment.cc
- Modules/PointSet/src/CMakeLists.txt
- Modules/PointSet/src/PointSetUtils.cc
- Modules/PointSet/src/SurfaceBoundary.cc
Auxiliary classes utilized in refactored and extended Mapping module, but are of common use.
> enh: Add auxiliary classes to iterate surface mesh boundary segments [PointSet]

- Applications/src/calculate-surface-attributes.cc
Minor bug in `calculate-pointset-attributes`. The `vtkPolyData` links/cells may not be available anymore after the `vtkPolyDataNormals` filter has run. Thus, build links right before the curvature filter is run instead. The `vtkPolyDataNormals` filter itself builds the links of the input.
> fix: Build links right before curvature filter is run [Applications]

- Applications/lib/python/mirtk/subprocess.py.in
- Applications/src/CMakeLists.txt
- Applications/src/calculate-element-wise.cc
The `mirtk` script maps `calculate` command to the new name `calculate-element-wise`.
> enh: Rename `calculate` tool to `calculate-element-wise` [Applications]

- Applications/src/calculate-surface-attributes.cc
- Applications/src/offset-surface.cc
- Applications/src/remesh.cc
- Applications/src/smooth-surface.cc
- Modules/PointSet/include/mirtk/EdgeTable.h
- Modules/PointSet/include/mirtk/MeshFilter.h
- Modules/PointSet/include/mirtk/MeshSmoothing.h
- Modules/PointSet/include/mirtk/SurfaceCollisions.h
- Modules/PointSet/include/mirtk/SurfaceCurvature.h
- Modules/PointSet/include/mirtk/SurfaceFilter.h
- Modules/PointSet/include/mirtk/SurfaceRemeshing.h
- Modules/PointSet/src/CMakeLists.txt
- Modules/PointSet/src/EdgeTable.cc
- Modules/PointSet/src/MeshFilter.cc
- Modules/PointSet/src/MeshSmoothing.cc
- Modules/PointSet/src/PointSetUtils.cc
- Modules/PointSet/src/SurfaceCollisions.cc
- Modules/PointSet/src/SurfaceCurvature.cc
- Modules/PointSet/src/SurfaceFilter.cc
- Modules/PointSet/src/SurfaceRemeshing.cc
- Modules/Registration/src/GenericRegistrationFilter.cc
Refactor class hierarchy of surface/volume mesh filters slightly and rename filters. Make `SurfaceCollisions` a subclass of the new `SurfaceFilter` instead of `Object` directly.
Before:
```
Object
PolyDataFilter
PolyDataSmoothing
PolyDataCurvature
PolyDataRemeshing
SurfaceCollisions
```
After:
```
Object
MeshFilter
MeshSmoothing
SurfaceFilter
SurfaceCurvature
SurfaceRemeshing
SurfaceCollisions
```
Used `SharedPtr` to optional `EdgeTable` input of mesh filters. When not set to a pre-computed edge table by the user of the filter, the filter instantiates an edge table itself if needed. No need for a separate `_EdgeTableOwner` flag when using smart pointers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> enh: Rename PolyDataFilter to MeshFilter and add SurfaceFilter base class

- CMake/Modules/FindSuiteSparse.cmake
- Scripts/install_depends.sh
The static `libsuitesparse-dev` package libraries on Ubuntu (at least up to 14.04) are not suiteable for shared linking because they were built without `-fPIC` option to create relocatable binary code. See [this bug report](https://bugs.launchpad.net/ubuntu/+source/suitesparse/+bug/1333214) found in the Ceres Solver installation guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/318)
> fix: FindSuiteSparse on Ubuntu and use PPA with bugfixed package

- .gitmodules
- Documentation/download.rst
- Documentation/install.rst
- Scripts/install_depends.sh
The `Mapping` module makes currently use of GPL'd code of Eigen3. It can therefore not be built with the MPLv2 subset of the Eigen header files currently included as Git submodule under `ThirdParty/Eigen`. Given the wide-spread use and popularity of these two libraries, remove them finally from the project and require a system installation instead. The `MIRTK/Boost` and `MIRTK/Eigen` GitHub projects may still remain there as these are the minimum required to build the core modules.... but basically unused now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/319)
> enh: Require system installation of Boost and Eigen3

- Modules/Common/include/mirtk/VtkMath.h
This should fix the build (on Ubuntu) with VTK 6.0 again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/320)
> fix: Add missing include of vtkConfigure.h in VtkMath.h [Common]

- Modules/IO/src/gifti/gifti_xml.cc
Closes #290.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/321)
> fix: Add missing fclose in error case to gxml_read_image GIFTI function [IO]

- Docker/Ubuntu/Dockerfile
The new `biomedia/ubuntu` Docker image on Docker Hub now includes an installation of Boost and Eigen 3.2.8. These system installations are now a requirement. Also, VTK was upgraded to VTK 7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/324)
> fix: Build of Docker image

- Modules/Transformation/src/MultiLevelFreeFormTransformation.cc
When computing the Jacobian of the local transformation only of a MFFD, the contribution from the global identity transformation was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/326)
> fix: Calculation of local MFFD Jacobian matrix [Transformation]

- Applications/src/compose-dofs.cc
The newly added option "interp_ffd" enables the output transformation to be represented using a single FFD.
I have found that this can dramatically reduce the size of the composed transformation at the cost of very trivial change of accuracy in representation. Representing using a single FFD also has the advantage of being a relatively smooth transformation compared to representing using a stack of FFDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/325)
> Added an option for compose_dofs

- Applications/src/register.cc
Order of `ARGUMENT` evaluation is from left to right instead of right to left as needed when using streaming operators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/331)
> fix: Parsing of register -par option arguments [Applications]

- Modules/Registration/src/GradientFieldSimilarity.cc
This changes fixes the fact that for gradient field similarities, it was not sufficient to set the flag for precomputation of gradients in the constructor (precomputation of gradients is crucial for these similarities to work). It has to be done in the GradientFieldSimilarity::InitializeInput method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/332)
> Force precomputation of image gradients for all gradient field similarities

- Modules/Image/src/ImageAttributes.cc
- Modules/Registration/src/GenericRegistrationFilter.cc
In this case, as common for longitudinal registration, don't use eigen decomposition to find a "suitable" orientation (which isn't working great anyway...), but instead simply use the common orientation of all input images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/338)
> fix: Orientation of FFD lattice when all fixed images have a common orientation

- Modules/Numerics/include/mirtk/SparseMatrix.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/342)
> fix: Endless loop during initialization of sparse matrix from tuples [Numerics]

- Modules/PointSet/include/mirtk/SurfaceCollisions.h
- Modules/PointSet/include/mirtk/Triangle.h
- Modules/PointSet/src/MeshFilter.cc
- Modules/PointSet/src/SurfaceCollisions.cc
- Modules/PointSet/src/SurfaceFilter.cc
- Add fast collision test based on distance of triangle centers only.
- Use angle between normal and difference vector of closest points / centers to detect false collisions. Previously, the vector from the center to the closest other point was used.
- Contains commit to just replace 'MMIRTK' by 'MIRTK' in source file preamble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/346)
> enh: Fast approximate collision test [PointSet]

- Modules/PointSet/include/mirtk/SurfaceRemeshing.h
These functions raise a "multiple definitions" error when MIRTK is included in an external library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/353)
> remeshing-inline-functions

- Modules/PointSet/test/testEdgeTable.cc
Fix up of previous change of `ReadPolyData` function signature.
> fix: Use new ReadPolyData functions in testEdgeTable [PointSet]

- Applications/src/convert-pointset.cc
- Modules/IO/include/mirtk/PointSetIO.h
- Modules/IO/src/PointSetIO.cc
Adds output function `WritePointSetTable` which is called by `WritePointSet` and `WritePolyData`, respectively, when the output file name extension is `.csv`, `.tsv`, or `.txt`. The point coordinates (optional) and point data arrays are written to either a comma or tab separated table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/355)
> enh: Table output of point data using convert-pointset [Applications]

- Modules/Common/include/mirtk/Common.h
- Modules/Common/include/mirtk/Exception.h
- Modules/Common/include/mirtk/Object.h
- Modules/Common/include/mirtk/String.h
- Modules/Common/src/CMakeLists.txt
- Modules/Common/src/Cifstream.cc
- Modules/Common/src/Cofstream.cc
These functions should be used instead of direct output to `cerr` + `exit` such that in later releases we may switch to throwing actual C++ exceptions.
> enh: Add Throw helper functions

- Modules/IO/include/mirtk/PointSetIO.h
- Modules/IO/src/PointSetIO.cc
- Fix up for PR #355.
- Also contains potential segfault fix of `ReadGIFTI`, e.g., when reading `.shape.gii` files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/358)
> fix: Output precision for point attributes to CSV export

- Applications/src/offset-surface.cc
When not exactly three positional arguments where given, a usage error was shown even though the third positional argument is optional. It is recommended to use the `-offset` option instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/359)
> fix: Positional argument parsing in offset-surface [Applications]

- Modules/Common/include/mirtk/Vtk.h
- Modules/Common/src/Vtk.cc
Just a minor function name change to be consistent with other functions such as `VtkDataTypeString` and `VtkAttributeTypeString`.
Keep deprecated function for grace period of transition to [future branch](https://github.com/schuhschuh/MIRTK/tree/future), where all uses of `NewVTKDataArray` were already replaced by `NewVtkDataArray`. This change allows selective merging of changes with the new function name in mind into the current master branch without breaking the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/365)
> enh: Rename NewVTKDataArray to NewVtkDataArray [Common]

- Applications/lib/python/mirtk/__init__.py.in
- Applications/lib/python/mirtk/subprocess.py.in
Convenience function that allows the use of Python dictionaries or ordered lists of tuples for command options instead. It also allows non-string arguments in the `argv` list of all call functions. Moreover, a single string is split into a list of arguments using `shlex.split`.
Example:
```python
import mirtk
mirtk.run('calculate-distance-map', args=[input_name, output_name],
opts={'distance': 'euclidean', '3D': None, 'isotropic': None})
mirtk.run('calculate-distance-map', args=[input_name, output_name],
opts=[('distance', 'euclidean'), '3D', 'isotropic'])
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/366)
> enh: Add mirtk.run function to Python module [Applications]

- Modules/Numerics/include/mirtk/Point.h
This allows a `mirtk::Point` to be used as argument for (VTK) functions that accept a `double[3]` C array pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/369)
> enh: Make Point non-Object, implicit cast to double* [Numerics]

- Applications/src/extract-surface.cc
- Modules/Common/include/mirtk/Options.h
The normals computed by `vtkMarchingCubes` are not very useful...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/371)
> enh: Use vtkPolyDataNormals for extract-surface -normals [Applications]

- Modules/PointSet/src/Triangle.cc
Apparently the triangle-triangle intersection test still produces quite some false positives... have no proper solution at hand right now, thus this temporary work around.
See related PR #315.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/378)
> fix: Temporary (slow) fix of triangle-triangle intersection test [PointSet]

- Modules/PointSet/include/mirtk/SurfaceRemeshing.h
- Modules/PointSet/src/SurfaceRemeshing.cc
Extends the `SurfaceRemeshing` filter to not just discard input cell data.
Moreover, categorical point data such as integer labels are now "interpolated" when inserting a new point according to a simple "weighted majority voting".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/380)
> enh: Copy cell data when subdividing cells [PointSet]

- Modules/Common/include/mirtk/Exception.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/383)
> fix: ToString template specialization for ErrorType [Common]

- Modules/PointSet/include/mirtk/PointSetUtils.h
- Modules/PointSet/include/mirtk/SurfaceBoundary.h
- Modules/PointSet/include/mirtk/SurfaceRemeshing.h
- Modules/PointSet/src/PointSetUtils.cc
- Modules/PointSet/src/SurfaceBoundary.cc
- Modules/PointSet/src/SurfaceRemeshing.cc
Modifies `SurfaceRemeshing` filter to preserve boundary edges of a non-closed surface mesh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/384)
> enh: Remesh surface with boundary edges [PointSet]

- Applications/src/CMakeLists.txt
- Applications/src/subdivide-brain-image.cc
- Applications/src/transform-points.cc
- Modules/Image/src/ConnectedComponents.cc
- Modules/Numerics/include/mirtk/Point.h
- Modules/Numerics/include/mirtk/PointSet.h
- Modules/Numerics/src/PointSet.cc
This command can be used to subdivide a brain image into disjoint right/left hemisphere, cortex, and brainstem+cerebellum regions given a structural segmentation such as the one produced by [Draw-EM](https://github.com/MIRTK/DrawEM) for neonatal brain images or [MALPEM](https://github.com/ledigchr/MALPEM) for adult brain images. The output of this command is the basis for reconstructing topologically correct brain surface meshes. See also PR #379 for merging these together again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/381)
> enh: Add subdivide-brain-image [Applications]

- Applications/src/CMakeLists.txt
- Applications/src/merge-surfaces.cc
- Modules/Image/src/ConnectedComponents.cc
- Modules/PointSet/include/mirtk/MeshFilter.h
- Modules/PointSet/include/mirtk/Stripper.h
- Modules/PointSet/include/mirtk/SurfacePatches.h
- Modules/PointSet/src/CMakeLists.txt
- Modules/PointSet/src/MeshFilter.cc
- Modules/PointSet/src/Stripper.cc
- Modules/PointSet/src/SurfacePatches.cc
When the input meshes are closed genus-0 surfaces following closely a given segmentation boundary (from a segmentation label image), the resulting mesh will also be a closed genus-0 surface enclosing the union of the volume enclosed by the input meshes. I am using this tool in particular to combine right and left hemisphere surface meshes and closed brainstem+cerebellum surface.
Still some work in progress, including:
This PR includes the following new mesh filters:
- `SurfacePatches`: Label connected surface regions where each internal edge has exactly two adjacent cells.
- `Splitter`: Wrapper for VTK's `vtkStripper` which better joins contiguous lines than the VTK implementation. Further needed for VTK 6 which contains no `vtkStripper::SetJoinContiguousLines` option.
Other …
> enh: Add tool to merge segmentation surface meshes [Applications]

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
- Modules/Image/src/DataOp.cc
- Modules/Numerics/include/mirtk/Vector3D.h
- Modules/Numerics/src/EnergyThreshold.cc
- Modules/PointSet/src/EdgeConnectivity.cc
Most interesting change is that the name of the point data array to use for `calculate-element-wise` for `-mask`, `-add`, `-sub`, `-mul`, and `-div` can now be specified as second argument or when the initial input point set contains the data array named as first argument, the file name is not required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/385)
> enh: Miscellaneous minor changes

- Modules/Image/include/mirtk/BaseImage.h
- Modules/Image/include/mirtk/InterpolateImageFunction.h
Unlike when transforming a point, the transformation of a vector must exclude the translation of the origin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/386)
> enh: Add ImageToWorld and WorldToImage for Vector3 [Image]

- Applications/src/calculate-surface-attributes.cc
- Modules/Image/include/mirtk/DataFunctions.h
- Modules/Image/include/mirtk/DataStatistics.h
- Modules/Image/include/mirtk/InterpolateImageFunction.h
- Modules/Numerics/include/mirtk/Vector3.h
- Modules/Numerics/src/Vector3.cc
- Modules/PointSet/include/mirtk/MeshSmoothing.h
- Modules/PointSet/src/MeshSmoothing.cc
Minor changes. Most important: `MeshSmoothing` filter averages VECTOR's differently. This was before done whenever the number of components was 3. But even with 3 components each one of these could be a separate scalar component rather.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/393)
> enh/fix: Miscellaneous

- Modules/PointSet/include/mirtk/ImplicitSurfaceUtils.h
Ensures that the distance in normal direction is at least the minimum surface distances known from the implicit surface function. Further, no need to compute distance in normal direction when max ray depth is less than the known minimum distance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/402)
> enh: Use max of min implicit surface and normal distance [PointSet]

- Modules/Common/include/mirtk/Math.h
- Modules/Numerics/include/mirtk/Point.h
- Modules/Numerics/include/mirtk/Vector3.h
- Modules/Numerics/src/Point.cc
- Modules/Numerics/src/Vector3.cc
- Add `SShapedMembershipFunction`.
- Add missing `Point::operator=(const Vector3&)` definition.
- Add further assignment operators.
- Add Vector3 from Point constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/400)
> enh: S-shaped membership function, Point/Vector3 assignment [Common,PointSet]

- Applications/src/calculate-surface-attributes.cc
- Modules/PointSet/include/mirtk/ImageSurfaceStatistics.h
- Modules/PointSet/src/CMakeLists.txt
- Modules/PointSet/src/ImageSurfaceStatistics.cc
- Add `ImageSurfaceStatistics` filter.
- Add `-patch*` options to `calculate-surface-attributes` to evaluate local image statistics at surface points.
- Add `-gradient*` options to evaluate image derivatives in normal direction.
In particular the `-gradient-angle` option is useful in quantifying whether the surface follows the image edges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/394)
> enh: Local image statistics/patches at surface points

- Modules/PointSet/src/Triangle.cc
Combining #398 and #378 as bounding sphere test alone is insufficient to discard false positive intersections. Eventually will have to fix `tri_tri_overlap_test_3d`...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/406)
> fix: Use distance_between_triangles when intersection suspected [PointSet]

- Modules/PointSet/src/Triangle.cc
Using `1e-6` resulted in non-detected intersections during white surface recon. Thus, be more conservative and "trust" initial intersection test when triangles seem to be pretty close anyway.
> fix: Change triangle distance threshold used to detect false positives [PointSet]

- Applications/src/dilate-scalars.cc
- Applications/src/erode-scalars.cc
The `vtkDataArray::DeepCopy` function apparently does not copy array name (and possibly neither component names) when using VTK 6.2. With version >=7.0 the array name seems to be copied as well. This change fixes it for all supported VTK versions and avoid use of `DeepCopy`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/414)
> fix: Output array name after dilate/erode-scalars [Applications]

- Applications/src/extract-pointset-surface.cc
- Add `-merge` and `-tolerance` options.
- Remove `-join` option. Use `merge-surfaces` tool instead (see #379).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/425)
> fix: Remove extract-pointset-surface -join option [Applications]

- Modules/PointSet/src/Triangle.cc
- Modules/PointSet/src/triangle_triangle_intersection.h
This should be the eventual and proper fix of the false intersection detection issue. Hope we still detect all actual intersections correctly after change of `CHECK_MIN_MAX` macro...
Closes #382.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/421)
> fix: Intersection test of nearly coplanar triangles [PointSet]

- Modules/Numerics/include/mirtk/LocalOptimizer.h
- Modules/Numerics/src/GradientDescent.cc
- Modules/Numerics/src/LocalOptimizer.cc
- Modules/Registration/include/mirtk/GenericRegistrationLogger.h
- Modules/Registration/src/GenericRegistrationLogger.cc
Add `_Converged` attribute to `LocalOptimizer` base class which may be used by observers such as the logger classes to determine whether the optimization converged due to a stopping criterion or if the max. number of iterations was reached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/427)
> fix: Emit IterationEndEvent also when optimization converged

- Modules/PointSet/include/mirtk/SurfaceCollisions.h
- Modules/PointSet/include/mirtk/Triangle.h
- Modules/PointSet/src/SurfaceCollisions.cc
Recheck collisions for nearby triangles, no matter their connectivity to the previously collided cells.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/428)
> fix: DeformableSurfaceModel::ResolveSurfaceCollisions

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
- Modules/Image/include/mirtk/DataOp.h
- Modules/Image/src/DataOp.cc
This change enables the use of the `calculate-element-wise` tool to process cell data of a VTK data set. It further adds a new `-map` option which can be used to change/swap segmentation labels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/429)
> enh: Process cell data with calculate-element-wise, -map option

- Modules/Common/include/mirtk/EnergyMeasure.h
- Modules/PointSet/include/mirtk/ImplicitSurfaceUtils.h
- Modules/PointSet/include/mirtk/RegisteredPointSet.h
- Modules/PointSet/src/RegisteredPointSet.cc
- Fix implicit surface distance when outside volume.
- Use `InitialStatus` for `-reset-status` and to save evaluation of implicit surface distance.
- Add `NormalForce`.
- Add `-fix-boundary` option.
- Add option to limit maximum point distance from input surface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/431)
> enh: deform-mesh

- Modules/PointSet/include/mirtk/RegisteredPointSet.h
- Modules/PointSet/src/MeshFilter.cc
- Modules/PointSet/src/RegisteredPointSet.cc
Uses a shared pointer to the edge table of a `RegisteredPointSet` such that it can be passed to functions and in particular `MeshFilter` instances and thus avoid recomputing the edge table.
> enh: Registered point set shared edge table

- Applications/src/transform-image.cc
This commit adds a `-type` option to `transform-image` which can be used to specify a desired output image data type. Moreover, the intermediate resampled image is always stored as floating point before casting it to the final output type to avoid any intermediate truncation.
> enh: Add transform-image output -dtype option [Applications]

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
Adds a third optional argument to the `-mask` option to be able to choose a background mask value different from zero.
> enh: Add calculate-element-wise -mask exclude value argument [Applications]

- Applications/src/close-image.cc
- Modules/Image/include/mirtk/Closing.h
- Modules/Image/include/mirtk/Dilation.h
- Modules/Image/src/CMakeLists.txt
- Modules/Image/src/Closing.cc
Make code used by `close-image` to pad the image before the dilation/erosion available as filter.
> enh: Add morphological image Closing filter [Image]

- Modules/IO/include/mirtk/PointSetIO.h
I moved the 2 includes outside the if, because the compiler gives me an error "invalid use of incomplete type" when compiling without MIRTK_IO_WITH_GIFTI
> compilation error

- Modules/Transformation/src/TransformationInverse.cc
The use of `BOOST_WORKAROUND` macro in `boost/math/tools/tuple.hpp` since Boost 1.62 breaks the build of the Transformation library. Issue reported here: https://svn.boost.org/trac/boost/ticket/12537
However, it seems the solution is to add the include `boost/math/config.hpp`.
> fix: BOOST_WORKAROUND issue with Boost 1.62 [Transformation]

- Applications/src/edit-dof.cc
Minor fix of clang warning regarding use of `HANDLE_STANDARD_OPTIONS` macro. Use `PARSE_STANDARD_OPTIONS` instead.
> fix: Paring of edit-dof options [Applications]

- Applications/lib/python/mirtk/subprocess.py.in
For execution of MIRTK commands within a Python pipeline script executed for a batch of data on a cluster, the number of threads must usually restricted to the number of requested resources. Hence, add this `mirtk.run` argument for convenience.
> enh: Add threads argument to mirtk.run Python function [Applications]

- Applications/src/average-dofs.cc
- Applications/src/close-image.cc
- Applications/src/compose-dofs.cc
- Applications/src/convert-dof.cc
- Applications/src/convert-image.cc
- Applications/src/copy-pointset-attributes-from-mat.cc
- Applications/src/dilate-image.cc
- Applications/src/dilate-scalars.cc
- Applications/src/downsample-image.cc
- Applications/src/edit-image.cc
- Applications/src/erode-image.cc
- Applications/src/erode-scalars.cc
- Applications/src/evaluate-cardiac-motion.cc
- Applications/src/evaluate-distortion.cc
- Applications/src/evaluate-dof.cc
- Applications/src/extract-connected-components.cc
- Applications/src/extract-connected-points.cc
- Applications/src/flip-image.cc
- Applications/src/info.cc
- Applications/src/invert-dof.cc
- Applications/src/open-image.cc
- Applications/src/reflect-image.cc
- Applications/src/resample-image.cc
- Applications/src/transform-points.cc
Always use `HANDLE_COMMON_OPTIONS` instead of `HANDLE_STANDARD_OPTIONS` even when command just ignores the additional common options.
> fix: All tools accept the common options (even if ignored) [Applications]

- Modules/Numerics/include/mirtk/SparseMatrix.h
- Modules/PointSet/include/mirtk/EdgeConnectivity.h
- Modules/PointSet/include/mirtk/EdgeTable.h
- Modules/PointSet/src/EdgeConnectivity.cc
- Modules/PointSet/src/EdgeTable.cc
A missing `GenericSparseMatrix` destructor caused a memory leak.
> fix: Sparse matrix destruction

- Modules/Common/include/mirtk/Memory.h
- Modules/Common/src/Memory.cc
Utility functions not currently in use. For debugging memory leaks.
> enh: Add functions to get current memory use [Common]

- Applications/src/calculate-surface-attributes.cc
- Applications/src/merge-surfaces.cc
- Applications/src/subdivide-brain-image.cc
- Modules/Common/include/mirtk/Assert.h
- Modules/Image/include/mirtk/BaseImage.h
- Modules/Image/include/mirtk/InterpolateImageFunction.h
- Modules/Numerics/include/mirtk/Point.h
- Modules/Numerics/include/mirtk/Vector3.h
- Modules/Numerics/include/mirtk/Vector3D.h
- Modules/Numerics/include/mirtk/Vector4D.h
- Modules/Numerics/src/Matrix3x3.cc
- Modules/Numerics/src/Vector3.cc
- Modules/PointSet/src/ImageSurfaceStatistics.cc
- Modules/PointSet/src/SurfaceRemeshing.cc
A reference member variable increases the size of the type.
> fix: No x/y/z references in Point/Vector3D/Vector4D, rename memers of Vector3

- Modules/IO/include/mirtk/NiftiImageReader.h
- Modules/IO/include/mirtk/NiftiImageWriter.h
- Modules/IO/src/NiftiImage.cc
- Modules/IO/src/NiftiImageReader.cc
- Modules/IO/src/NiftiImageWriter.cc
- Modules/Image/src/ImageReaderFactory.cc
- Modules/Image/src/ImageWriterFactory.cc
Fixes memory leaks caused by assertions when built with `NDEBUG` not defined. Further introduces use of `UniqePtr` in NIfTI I/O filters to reduce risk of memory leaks.
> fix: Memory leaks in Debug config

- Applications/lib/python/mirtk/subprocess.py.in
This is needed for Python 3 when the returned value should be a `str` rather than a bytes-like object.
> enh: Decode command output by default as UTF-8 [Applications]

- Applications/src/evaluate-similarity.cc
- Applications/src/subdivide-brain-image.cc
- Modules/IO/src/PointSetIO.cc
- Modules/Image/include/mirtk/DataStatistics.h
- Modules/PointSet/src/PointSetUtils.cc
- Modules/PointSet/src/Stripper.cc
Fix warnings about implicit type cast with potential loss of precision as well as comparisons of signed with unsigned values.
> fix: Implicit type cast and signed/unsigned comparison warnings

- Modules/Common/include/mirtk/Stream.h
So far always used `cout.flush()` but this allows `cout << flush`.
> enh: Add std::flush to mirtk namespace [Common]

- Modules/PointSet/include/mirtk/EdgeConnectivity.h
- Modules/PointSet/src/EdgeConnectivity.cc
`RegisteredPointSet` now calls `NewShared<EdgeConnectivity>(dataset, radius, edgeTable)` instead of the `Initialize` function. This change silently introduced a bug where radius would be interpreted as max edge connectivity instead and the wrong constructor being called.
> fix: Add missing EdgeConnectivity constructor called by RegisteredPointSet [PointSet]

- Applications/src/transform-image.cc
The type used for the padding value in `transform-image` was `int` although set to `NaN` or `-inf`, respectively.
> fix: Type and parsing of transform-image padding value [Applications]

- .gitmodules
- BasisProject.cmake
Adds a new optional package intended to contain various utility functions useful for writing pipeline or other pre- or post-precessing scripts. This extra package currently only contains a Python module to render 2D screenshots of NIfTI volume slices with or without surface contours overlaid. Required by the [cortical surface evaluation tools](https://github.com/schuhschuh/CorticalSurfaceEvaluation) used to assess the quality of surfaces produced by the MIRTK `recon-neonatal-cortex` command.
> mod: Add optional Scripting package

- Modules/Common/include/mirtk/EnergyMeasure.h
- Modules/Registration/include/mirtk/IntensityCrossCorrelation.h
- Modules/Registration/include/mirtk/NormalizedIntensityCrossCorrelation.h
- Modules/Registration/include/mirtk/SimilarityMeasure.h
- Modules/Registration/src/ImageSimilarity.cc
- Modules/Registration/src/IntensityCrossCorrelation.cc
- Modules/Registration/src/NormalizedIntensityCrossCorrelation.cc
Missing neighborhood iterator `SetChannel(0)` possibly after change of region iterator implementation. However, removed use of iterator all together as there is little benefit to using it. Implemented global NCC similarity measure for window size = 0.
> enh/fix: Normalized cross correlation [Registration]

- Modules/Image/src/GenericImage.cc
Fix of `-=`, `+=`, `*=`, and `/=` operators of `GenericImage` class. Indirectly fixes inversion of SV FFD transformation which uses `_CPImage *= -1.0`, where `_CPImage` is a vector-valued image.
The voxel_cast to double only works for scalar images, but not vector-valued images. One fix would be to use voxel_cast<RealType>, but rather let the VoxelType implement the respective arithmetic operator with double scalar argument on the right-hand side.
> fix: Scalar operators of GenericImage [Image]

- Modules/Registration/src/GenericRegistrationFilter.cc
- Modules/Transformation/src/BSplineFreeFormTransformationSV.cc
The result of the registration with energy function `SIM(I(1) o T^-0.5, I(2) o T^0.5)` for the reversed order of input images, e.g., `-image a.nii.gz b.nii.gz` vs. `-image b.nii.gz a.nii.gz`, should be the exact inverse (i.e., `v_{ba} = - v_{ab}`) of each other. Due to minor bugs in the setup of the registration filter, this was not the case when cropping of the SV FFD lattice was enabled. This has been fixed and moreover the cropping is disabled for SV/TD FFD models by default.
> fix: Symmetry with symmetric SV FFD energy

- Modules/Image/include/mirtk/ImageGradientFunction.h
- Modules/Registration/include/mirtk/GenericRegistrationFilter.h
- Modules/Registration/src/GenericRegistrationFilter.cc
- Modules/Transformation/include/mirtk/RegisteredImage.h
- Modules/Transformation/src/RegisteredImage.cc
When using a B-spline interpolator, the coefficients were recomputed upon each update of the transformed image which slows down the registration quite a lot and is unnecessary. Instead, keep the interpolators alive between update calls to avoid unnecessary re-computations.
This PR also includes a small change of evaluating values outside the domain for which no boundary condition has to be applied to avoid sharp boundaries in the transformed image.
Further, the pre-computation of source image gradients is automatically enabled when the interpolation mode is not Linear, which is the only one for which there exists an on-the-fly ImageGradientFunction subclass at the moment. Still need to provide ones for the B-spline interpolation modes.
> enh: Registered image cache interpolators

- Modules/Image/include/mirtk/BSplineInterpolateImageFunction.h
- Modules/Image/include/mirtk/BSplineInterpolateImageFunction.hxx
- Modules/Image/include/mirtk/BaseImage.h
- Modules/Image/include/mirtk/CubicBSplineInterpolateImageFunction.h
- Modules/Image/include/mirtk/CubicBSplineInterpolateImageFunction.hxx
- Modules/Image/include/mirtk/FastCubicBSplineInterpolateImageFunction.h
- Modules/Image/include/mirtk/FastCubicBSplineInterpolateImageFunction.hxx
- Modules/Image/include/mirtk/GenericImage.h
- Modules/Image/include/mirtk/ImageToInterpolationCoefficients.h
The default interpolation without extrapolator as well as the interpolation with padding value would produce incorrect results at the boundary. Also, filling in the background by propagating the foreground boundary values reduces large gradients in the coefficients at the boundary.
> fix: B-spline interpolators

- Modules/Registration/src/GenericRegistrationFilter.cc
- Modules/Transformation/src/RegisteredImage.cc
When the images are cropped, the SV/TD FFD needs some extra margin to avoid extrapolation artefacts.
> fix: Registration SV/TD FFD domain and RegisteredImage rescaling

- Modules/Registration/src/GenericRegistrationFilter.cc
Fixes invalid memory read issues with `register -mask` option on final level.
> fix: Resampling of domain mask [Registration]

- Applications/src/invert-dof.cc
The error evaluation is costly. Better to disable by default.
> enh: Do not evaluate inverse error by default [Applications]

- Applications/src/average-dofs.cc
When all input transformations have the same FFD type and no multi-level transformation, the output should be of the same type as the input transformations without any multi-level transformation. PR includes smaller C++11 improvements such as use of UniquePtr and nullptr.
> fix: average-dofs -v segfault, output FFD type

- Applications/src/average-images.cc
- Modules/Image/include/mirtk/GenericImage.h
- Modules/Image/include/mirtk/ImageAttributes.h
- Modules/Image/src/GenericImage.cc
- Modules/Image/src/ImageAttributes.cc
The Laplacian based average image sharpening is done by the ANTs AverageImages tool used for atlas construction.
> enh: average-images input/output normalization and output sharpening

- Modules/Image/include/mirtk/BaseImage.h
- Modules/Image/include/mirtk/HashImage.h
- Modules/Image/include/mirtk/HashImage.hxx
- Modules/Image/src/BaseImage.cc
- Modules/Image/src/GenericImage.cc
`BaseImage(attr, 1)` should result in a scalar valued image regardless of the `attr._t` value.
> fix: Number of components argument handling in BaseImage constructor [Image]

- Applications/src/evaluate-similarity.cc
- Modules/Transformation/src/RegisteredImage.cc
- A homogeneous coordinate transformation given as `-dofin` was not applied to the source image and thus had no effect because the transformation was set after `RegisteredImage::Initialize` had been called already.
- Add optional `-table` output file name argument.
- Update registered images after each similarity evaluation because NCC for example forces a rescaling of intensities to the range [0, 1].
> fix/enh: evaluate-similarity [Applications]

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
- Modules/Image/include/mirtk/DataOp.h
- Modules/Image/include/mirtk/DataStatistics.h
- Modules/Image/src/DataOp.cc
- Use smart pointers to avoid memory leaks.
- Fix `-mask` option arguments.
- Add `-sum` option.
> enh: calculate-element-wise [Applications]

- Applications/src/CMakeLists.txt
- Applications/src/aggregate-images.cc
- Modules/Common/include/mirtk/Algorithm.h
- Modules/Image/include/mirtk/BaseImage.h
Besides `average-images`, this command can be used to evaluate measures of dispersion of the to-be-averaged intensity values.
- Fix `ImageBase::IsForeground` to use tolerance of 1e-6 when comparing image value to background value set as double floating point number.
> add: aggregate-images with voxel-wise measures of dispersion [Applications]

- Applications/src/transform-image.cc
- Modules/Transformation/include/mirtk/ImageTransformation.h
- Modules/Transformation/src/ImageTransformation.cc
No need to compose transformations beforehand using `compose-dofs`. Instead, use `-dofin` or `-dofin_i/-invdof` options multiple times to compose the total transformation.
> enh: transform-image with composite transformation [Applications]

- Applications/src/compose-dofs.cc
Only the first level of a Fluid MFFD was pushed onto the composite output transformation.
> fix: compose-dofs with Fluid MFFD [Applications]

- Modules/Numerics/src/Matrix.cc
When no weights are associated with any input transformation of `average-dofs`, it would crash with segfault when the `-log-euclidean` option is used.
> fix: Unweighted LogEuclideanMean of affine transformations [Matrix]

- Applications/lib/python/mirtk/subprocess.py.in
Otherwise, the subprocess output may be printed before anything the main Python process has buffered.
> fix: Flush stdout before running subprocess [Applications]

- Applications/src/average-images.cc
- Modules/Transformation/include/mirtk/BSplineFreeFormTransformation3D.h
- Modules/Transformation/include/mirtk/BSplineFreeFormTransformation4D.h
- Modules/Transformation/include/mirtk/BSplineFreeFormTransformationSV.h
- Modules/Transformation/include/mirtk/FreeFormTransformation.h
- Modules/Transformation/include/mirtk/FreeFormTransformation3D.h
- Modules/Transformation/include/mirtk/FreeFormTransformation4D.h
- Modules/Transformation/include/mirtk/LinearFreeFormTransformation3D.h
- Modules/Transformation/include/mirtk/LinearFreeFormTransformation4D.h
- Modules/Transformation/include/mirtk/MultiLevelFreeFormTransformation.h
- Modules/Transformation/include/mirtk/MultiLevelStationaryVelocityTransformation.h
- Modules/Transformation/include/mirtk/MultiLevelTransformation.h
- Modules/Transformation/include/mirtk/PartialBSplineFreeFormTransformationSV.h
- Modules/Transformation/include/mirtk/PartialMultiLevelStationaryVelocityTransformation.h
- Modules/Transformation/include/mirtk/Transformation.h
For a SV FFD, when `t0` is not specified explicitly, it should be integrated over the default cross-sectional time interval. Setting `t0 = -1` doesn't allow us to identify if it was specified or not as time values can be negative. Thus, use NaN instead.
> fix: Default t0 argument of Transformation functions, average-images [Transformation]

- Applications/src/register.cc
- Modules/Common/include/mirtk/EnergyMeasure.h
- Modules/Registration/include/mirtk/GenericRegistrationFilter.h
- Modules/Registration/include/mirtk/MeanSquaredDisplacementError.h
- Modules/Registration/src/CMakeLists.txt
- Modules/Registration/src/GenericRegistrationFilter.cc
- Modules/Registration/src/MeanSquaredDisplacementError.cc
- Modules/Registration/src/RegistrationEnergy.cc
- Modules/Registration/src/RegistrationEnergyParser.h
- Modules/Transformation/src/FreeFormTransformation.cc
The `MeanSquaredDisplacementError` can be used to constrain the transformation to resemble another such as a mean longitudinal deformation or a approximated composed transformation.
> enh: Add register -disp option and corresponding MSDE term [Registration]

- Modules/Registration/src/ImageSimilarity.cc
Bug introduced with one of the recent PRs. The one adding the "Image similarity foreground" parameter. In particular [this line/commit](https://github.com/BioMedIA/MIRTK/pull/538/commits/435f67f0d25f78445e4b18ce576362b8bc5d6de8#diff-2f8cc55d0dff18cc4a495480f877384fR424) of PR #538.
> fix: Parsing of parameters in ImageSimilarity::Set [Registration]

- Modules/PointSet/src/SurfaceCollisions.cc
- Modules/PointSet/src/Triangle.cc
Segfault caused by changes of `vtkIntersectionPolyDataFilter::TriangleTriangleIntersection` which requires a tolerance value >0 (1e-9 was not large enough for cortical meshes either).
See also upstream bug report for VTK>=7.1 [here](https://gitlab.kitware.com/vtk/vtk/issues/17012).
> fix: Triangle-triangle intersection test

- Applications/src/transform-image.cc
One of the recent changes for resampling label images must have introduced this bug. The default output data type of the transformed image should be identical to the input source image, not double.
> fix: Default transform-image output -dtype [Applications]

- Modules/Common/include/mirtk/Allocate.h
- Modules/Common/include/mirtk/Exception.h
The exit code has thus far always been 1 on error. Now, the exit code reflects the `ERR_*` error code of the `Throw` function used to raise errors. In particular the new memory allocation failed error can be used to determine that a batch job should possibly be restarted on another compute node instead of just giving up immediately.
See also PR #566.
> enh: Use ERR_ enum value as exit code in Throw, new ERR_Memory allocation failed error [Common]

- Applications/lib/python/mirtk/subprocess.py.in
By default, `mirtk.run` throws a `subprocess.CalledProcessError` exception when the program returns a non-zero exit code. When not handled, the calling Python script exits with code 1. With the new option, the exception is dealt with by `mirtk.run` which then exits the calling Python script with the same exit code as the subprocess.
> enh: Add exit_on_error option to mirtk.run [Applications]

- Applications/src/compose-dofs.cc
- Modules/Transformation/include/mirtk/FluidFreeFormTransformation.h
- Modules/Transformation/src/FluidFreeFormTransformation.cc
Make auxiliary functions used to compose transformations into single `FluidFreeFormTransformation` available via the library function `FluidFreeFormTransformation::PushTransformation` in order to allow for these to be reused elsewhere.
> enh: Move code from compose-dofs to FluidFreeFormTransformation [Transformation,Applications]

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
This new option argument can be used for example to normalize voxel-wise weights before multiplication with another image.
> enh: calculate-element-wise divide-by "sum" [Image,Applications]

- Applications/src/aggregate-images.cc
- Modules/Image/include/mirtk/Histogram1D.h
- Modules/Image/src/Histogram1D.cc
New `aggregate-images` options:
- `-mask` to restrict output to the given foreground region.
- `mode` to output smallest voxel-wise histogram mode.
- `label-consistency` to output voxel-wise mean pair-wise DSC.
- output `-datatype` option.
> enh: aggregate-images 'mode' and 'label-consistency' output [Applications]

- Modules/Image/include/mirtk/VoxelCast.h
Change `voxel_cast` for `float` and `double` to integer type to `round` value before `static_cast`.
> enh: Use rounding function when casting floating point to integer type [Image]

- Modules/Common/include/mirtk/Common.h
This header is included by other headers anyway, but this way it is listed explicitly.
> fix: Include Stream.h in Common.h [Common]

- Modules/Transformation/src/BSplineFreeFormTransformationSV.cc
Fixes endless recursion due to virtual function call in SV FFD gradient computation with `Integration method = SS` and `No. of BCH terms = 0`.
> fix: SS gradient computation in SV FFD [Transformation]

- Modules/Common/include/mirtk/String.h
Fixes case insensitive comparison of strings using `iequal` function. Return value was always `false`. This caused unrecognized registration parameter values such as `Integration method` because `iequal` is used in some `FromString` implementations.
> fix: Case insensitive string comparison function iequal [Common]

- Applications/src/CMakeLists.txt
- Applications/src/average-measure.py
Add `average-measure` script which is used to compute mean of voxel-wise image evaluation measure within specified ROIs. These measures are usually computed using the `aggregate-images` command and the ROIs may be brain tissue/structure probability maps.
> add: average-measure script [Applications]

- Applications/lib/python/mirtk/subprocess.py.in
Convenience `-workdir` option of `mirtk.run` function to safely change working directory before executing command and restoring previous working directory afterwards or upon error.
> enh: Add workdir argument to mirtk.run function [Applications]

- Applications/src/evaluate-jacobian.cc
- Modules/Image/src/ScalingAndSquaring.cc
Negative Jacobian determinants reported by `evaluate-jacobian` for a SV FFD with `FastSS` integration method is due to the final upscaling step (not sure why... B-spline interpolator issue?).
> fix: Negative Jacobian values caused by upsampling [Image]

- Modules/Common/include/mirtk/Exception.h
Enum value `ERR_None` not handled by `ToString` function.
> fix: Warning of ERR_None not being handled in ToString [Common]

- Modules/Registration/src/GenericRegistrationFilter.cc
Fix segfault caused by uninitialised member variable (pointer) of `GenericRegistrationFilter`.
> fix: Uninitialized _TargetTransformation pointer of GenericRegistrationFilter [Registration]

- Applications/src/evaluate-distance.cc
- Modules/Common/include/mirtk/Algorithm.h
Add options to `evaluate-distance` command:
- `-mask-name`, `-mask-erosion`, `-mask-dilation` to evaluate distance only for masked target points.
- `-table`, `-[no]header`, `-[no]append`, `-digits` for output to CSV/TSV file.
> enh: evaluate-distance target point mask and table output options [Applications]

- Applications/src/average-dofs.cc
- Applications/src/compose-dofs.cc
The SVFFD transformation model stores additional parameters used for exponentiation and application of BCH formula in the class attributes/`.dof` file. This PR modifies `average-dofs` and `compose-dofs` to copy those from the first input SVFFD to the output file.
> fix: Preserve parameters of SVFFD after averaging or composition [Applications]

- Applications/lib/python/mirtk/subprocess.py.in
Instead of: ```mirtk.run(command, args=[a, b, c], opts=dict(name=value))```
simply write: ```mirtk.run(command, a, b, c, name=value)```
The old syntax is still supported for backwards compatibility and to still support an ordered dictionary as `opts` argument.
> enh: Use *args and **kwargs of mirtk.subprocess.run instead of “args” list and “opts” dictionary [Applications]

- Modules/Numerics/include/mirtk/Eigen.h
This warning was observed with an older version of the Eigen3 library when compiling with Clang on Ubuntu 14.04. The warning is not seen on macOS with a later version installed using Homebrew.
> enh: Disable 'register' storage class specifier is deprecated warning [Numerics]

- .travis.yml
- Scripts/install_depends.sh
- Scripts/travis.sh
- Reduce number of Travis CI macOS builds to one to avoid having to wait for two jobs to wait for each CI build given that `travis-ci.org` has lower capacity for macOS jobs. Only one build without VTK on Ubuntu should be sufficient to ensure everything works fine when `WITH_VTK=OFF`.
- Build only required VTK modules from source on macOS. Cache custom installation.
> travis: Reduce macOS jobs, cache VTK installation

- Modules/Image/src/Histogram1D.cc
- Modules/Image/src/Histogram2D.cc
> fix: Histogram1D and Histogram2D Read/Write magic string “irtk” prefix [Image]

- Applications/src/register.cc
- Modules/Registration/include/mirtk/GenericRegistrationFilter.h
- Modules/Registration/src/GenericRegistrationFilter.cc
- Convenience `-output` option of `register` command to write transformed image. Works only for standard pairwise registrations. Otherwise use of `transform-image` is still recommended.
- Add `-background` option to specify `Background value` without `-parin` file.
- Fix constness of `InterpolationMode` and `ExtrapolationMode` getter functions.
Closes #261.
> enh: register -output and -background options

- Applications/src/register.cc
- Modules/Image/include/mirtk/InterpolationMode.h
- Modules/Transformation/include/mirtk/RegisteredImage.h
- Modules/Transformation/src/RegisteredImage.cc
When the user specifies a `Background value`, the default interpolation mode used by `RegisteredImage` to resample the input image given the current transformation estimate is "with padding". This also includes a fix of the background value in the pre-computed transformed first and second order derivatives, which is now `NaN` instead of 0.
When the user chooses `Interpolation mode = Linear` or any other interpolation "without padding", the pre-computed derivatives, including the optional previous Gaussian smoothing, is done without considering the background value, i.e., across foreground/background boundary. Only when the interpolation mode is "with padding", the background is excluded from these steps.
Normally it is advisable to exclude the background, i.e., to use a "with padding" …
> fix: Interpolation with padding by default [Transformation]

- Applications/src/register.cc
- Modules/Registration/include/mirtk/GenericRegistrationFilter.h
- Modules/Registration/src/GenericRegistrationFilter.cc
- Modules/Registration/src/GenericRegistrationLogger.cc
- Use `-dofin guess` for previous behaviour also when `-model FFD`.
Closes #330.
> enh: Use identity as initial guess of deformable models [Registration,Applications]

- Modules/Registration/src/GenericRegistrationFilter.cc
Get rid of OS specific code using `strtok`. Instead use the newer `mirtk::Split` function.
> enh: Use Split function to parse -model parameter [Registration]

- .bintray.yml
- .travis.yml
- Documentation/static/logo.svg
- README.md
- Scripts/install_depends.sh
- Scripts/make_appimage.sh
- Scripts/travis.sh
The AppImage created from the latest master `HEAD` is deployed automatically to [bintray.com](https://bintray.com/schuhschuh/AppImages/MIRTK/master#files). When the commit is tagged, the AppImage is uploaded to the tagged release on GitHub.
Example use on Linux:
```
wget -O mirtk https://bintray.com/schuhschuh/AppImages/download_file?file_path=MIRTK-latest-x86_64-glibc2.14.AppImage
chmod a+x mirtk
./mirtk -h
./mirtk register -version
./mirtk construct-atlas -h
```
Hence, the `mirtk` AppImage acts like a ELF binary that simply can perform all the MIRTK commands. The only requirement at this moment is a Python installation. May include it at some point in the AppImage, but I guess that won't be necessary.
Closes #221.
> enh: Make AppImage from Travis CI build

- .travis.yml
- Scripts/install_mirtk_appimage.sh
- Scripts/make_appimage.sh
Include the pre-built `view` binary from https://bintray.com/schuhschuh/generic/MIRTKViewer in AppImage deployed by Travis CI build.
> enh: Include 'view' binary in AppImage

- Applications/lib/python/mirtk/atlas/spatiotemporal.py
Python module should not have a she-bang as it's not executable. Instead, insert license information as comment.
> fix: Replace she-bang with license information in ‘spatiotemporal’

- Applications/lib/python/mirtk/__init__.py.in
- Applications/lib/python/mirtk/subprocess.py.in
This change enables the calling of MIRTK commands from Python using the syntax demonstrated by the following example:
```python
import mirtk
mirtk.info(version=None)
mirtk.register("target.nii.gz", "source.nii.gz", dofin="rigid.dof", dofout="ffd.dof.gz", model="FFD")
```
instead of
```python
import mirtk
mirtk.run("info", version=None)
mirtk.run("register", "target.nii.gz", "source.nii.gz", dofin="rigid.dof", dofout="ffd.dof.gz", model="FFD")
```
The `mirtk.<command>` wrappers for `mirtk.subprocess.run` are added dynamically. Hence, no need to update the `mirtk/__init__.py.in` file when a new command is added.
This PR also contains a fix of the `mirtk.subprocess.remove_kwargs` function for Python 3.
> enh: Call commands using 'mirtk.<command>', fix Python 3 error [Applications]

- Applications/lib/python/mirtk/__init__.py.in
Fixup for #613.
- Enables calling also commands that have a dash (`-`) in their name.
- Implicitly checks existence of command binary using `mirtk.subprocess.path`.
> fix: Use underscores instead of dashes in ‘mirtk.<command>’ call [Applications]

- Applications/lib/python/mirtk/__init__.py.in
- Applications/lib/python/mirtk/atlas/spatiotemporal.py
- Applications/lib/python/mirtk/subprocess.py.in
- Specify command options with dashes as kwargs using underscores instead.
- Add `onexit` kwarg which enables return of exit code or command output.
- Add `onerror` kwarg with more options than the now deprecated `exit_on_error` switch.
- Fix availability of `mirtk.subprocess` when using `import mirtk` (fixup for #613).
```python
import sys
import mirtk
output = mirtk.info("image.nii.gz", showcmd=True, onerror='exit', onexit='output')
mirtk.register("foo.nii.gz", "bar.nii.gz", onerror=None)  # ignore error, return None anyways
exit_code = mirtk.register("foo.nii.gz", "bar.nii.gz", onerror='none', onexit='returncode')
if exit_code != 0:
sys.stderr.write("Command failed!")
sys.exit(42)
```
> enh: Replace ‘_’ in command option kwargs by ‘-‘, add onexit and onerror [Applications]

- Applications/src/register.cc
- Modules/Registration/src/GenericRegistrationFilter.cc
Split `Energy function` over multiple lines using MATLAB style line continuation, e.g.,
```
Energy function = SIM[Image dissimilarity](I(1), I(2) o T)...
+ .001 BE[Bending energy](T)...
+ 0 TP[Topology preservation](T)...
+ 0 VP[Volume preservation](T)
```
> enh: Split ‘Energy function’ over multiple lines using ’…’ [Registration]

- Applications/src/aggregate-images.cc
Add also variance (`var`, `variance`) mode to `aggregate-images`, not only standard deviation.
> enh: Add ‘variance’ mode to aggregate-images [Applications]

- Applications/src/extract-image-region.cc
- Modules/Common/include/mirtk/Path.h
- Modules/Common/src/Path.cc
The `FileName` function discards the directory path. Use new `FilePrefix` function to get the full output file path without extension.
Fixes for #624.
> fix: extract-image-region -split output file paths

- Applications/src/average-images.cc
* Fix parsing of positional arguments.
* Create a separate probability map (average) for each label of multiple hard segmentations.
```
mirtk average-images prob_%02d.nii.gz seg1.nii.gz seg2.nii.gz seg3.nii.gz... -labels
```
> enh: Create separate average for each segmentation label [Applications]

- Scripts/travis.sh
A mistake in the `travis.sh` script used to configure the CI build caused not all modules to be built.
> fix: Travis CI missing CMake MODULE_*=ON arguments

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataStatistics.h
Count the number of data values (voxels) inside the current mask.
> enh: Add calculate-element-wise -count option [Applications,Image]

- Applications/src/init-dof.cc
- Modules/Image/src/ImageAttributes.cc
- Modules/Numerics/include/mirtk/Matrix.h
- Modules/Numerics/include/mirtk/Point.h
- Modules/Numerics/src/Matrix.cc
- Modules/Transformation/include/mirtk/HomogeneousTransformation.h
Image axes had been flipped (opposite sign) after re-applying the `edit-image -reset -dofout`.
> fix: Apply affine header transformation

- Modules/Registration/src/GenericRegistrationFilter.cc
This is needed because (for now) `AffineTransformation::PutMatrix` (and other functions) force passive parameters to be equal the default value corresponding to the identity mapping. Eventually, it might be better when `Allow ... = No` options would only impact `AffineTransformation::Update`. However, the current behavior is used in other places already such as `init-dof` in particular. Thus, fix it for now in the least intrusive manner.
> fix: No centering translation in dimension where this is disabled [Registration]

- Applications/src/convert-dof.cc
Previous conversion only valid for latest NiftyReg version. This PR enables converted SVF spline computed with NiftyReg 1.3.9 to be converted to MIRTK SVFFD.
> fix: Conversion of NiftyReg F3D velocity field computed with v1.3.9 [Applications]

- Modules/Numerics/include/mirtk/ConjugateGradientDescent.h
- Modules/Numerics/include/mirtk/ObjectiveFunction.h
- Modules/Numerics/src/ConjugateGradientDescent.cc
- Modules/Registration/include/mirtk/RegistrationEnergy.h
- Modules/Registration/src/RegistrationEnergy.cc
Adds option `Conjugate total energy gradient` which is `On` by default. When `Off`, only the gradient of the data terms is conjugated before the gradient of the penalty terms are added to this conjugate gradient.
> enh: Conjugate gradient of data fidelity terms only [Registration]

- Modules/Image/include/mirtk/CubicBSplineConvolution.h
- Modules/Image/include/mirtk/GaussianBlurring.h
- Modules/Image/include/mirtk/GaussianBlurringWithPadding.h
- Modules/Image/include/mirtk/SeparableConvolution.h
- Modules/Image/src/CMakeLists.txt
- Modules/Image/src/CubicBSplineConvolution.cc
- Modules/Image/src/GaussianBlurring.cc
- Modules/Image/src/GaussianBlurringWithPadding.cc
- Modules/Image/src/SeparableConvolution.cc
- Modules/Transformation/include/mirtk/BSplineFreeFormTransformation3D.h
- Modules/Transformation/src/BSplineFreeFormTransformation3D.cc
- Modules/Transformation/src/FreeFormTransformation.cc
- New `ConvolutionFilter` base class used also for `GaussianBlurring`.
- Implements FFD gradient calculation using cubic B-spline convolution filter.
- Implements the "Directly manipulated FFD" scheme, where the parametric gradient is obtained by directly approximating the voxel-wise (non-parametric) gradient field by a spline function.
> enh: Approximate FFD gradient calculations

- Modules/Registration/src/GenericRegistrationFilter.cc
Allow Windows-style newline breaks in registration parameters file.
> fix: Trim \r character at end of line when parsing register parameters [Registration]

- Applications/src/evaluate-overlap.cc
> fix: Parsing of ‘false negative rate’ string in evaluate-overlap [Applications]

- Examples/helloworld/CMakeLists.txt
- Examples/helloworld/README.md
- Examples/helloworld/flip.cc
Add a simple "hello world" example program to show how to set up a project that builds against MIRTK.
I hope the `CMakeLists.txt` I've done is correct. I found I had to have `find_package(VTK)` or linking would fail with:
```
[100%] Linking CXX executable flip
/usr/bin/ld: cannot find -lvtkCommonCore
/usr/bin/ld: cannot find -lvtksys
... etc.
```
Perhaps `find_package(MIRTK)` should do this automatically?
I needed the explicit `include(MIRTKTargets)` to get `mirtk::LibCommon` and `mirtk::LibPointSet` defined. Perhaps this should also be included automatically by `find_package(MIRTK)`?
> Add a helloworld example

- .gitmodules
- .travis.yml
- Applications/lib/python/mirtk/subprocess.py.in
- Applications/tools/mirtk.py
- BasisProject.cmake
- Documentation/CMakeLists.txt
- Documentation/getstarted.rst
- Scripts/install_depends.sh
- Scripts/install_mirtk_appimage.sh
- Scripts/make_appimage.sh
- Scripts/travis.sh
The MIRTK/Viewer package provides the `display` and `view` commands.
> Add viewer module

- Modules/Image/include/mirtk/HashImage.hxx
Template specialization caused compilation error with MSVC 2015.
> fix: Remove explicit HashImage::ImageToVTK template specialization for Matrix3x3

- Modules/Image/src/GenericImage.cc
Too many explicit template instantiations in single compilation unit result in "internal compiler error" with newer Microsoft compilers, in particular toolset "v141" of Visual Studio 2017.
> fix: Internal compiler error when compiling GenericImage::GetMinMax with MSVC 2017

- Modules/Transformation/src/MultiLevelFreeFormTransformation.cc
Loop variable lvl was incremented twice each iteration.
> fix: MultiLevelFreeFormDeformation::Approximate function

- CMake/Modules/FindARPACK.cmake
When using libparpack installed with Homebrew, undefined symbols were encountered. Use of libarpack fixed it.
> fix: Prefer “libarpack” over “libparpack” in FindARPACK

- CMake/Modules/FindTBB.cmake
When TBB:: import targets already exist, update their properties.
> fix: Update properties of existing TBB import targets

- CMake/Basis/BasisSettings.cmake
- CMake/Basis/ProjectTools.cmake
Add new BASIS_UNINSTALLER option which can be used to request installation of `uninstall-mirtk` script. By default, no uninstall script is being installed any longer as this script makes the installation no longer relocatable.
Closes #674 .
> enh: Add BASIS_UNINSTALLER option which is OFF by default

- Modules/PointSet/include/mirtk/SurfaceCollisions.h
- Modules/PointSet/src/SurfaceCollisions.cc
If VTK_USE_64BIT_IDS is not defined, vtkIdType is an alias for `int`. Hence, `SurfaceCollisions::GetCollisionType(int)` is the same as `SurfaceCollisions::GetCollisionType(vtkIdType)`. In this case, get rid of the redundant definition.
Closes #676.
> fix: SurfaceCollisions::GetCollisionType(vtkIdType)

- Applications/src/smooth-surface.cc
> fix: AreaWeighted smoothing function requires vtkPolyData::BuildLinks

- Applications/src/calculate-element-wise.cc
- Modules/Image/include/mirtk/DataFunctions.h
CC @soundray.
```
$ mirtk calculate-element-wise seg95.nii.gz -extrema -mod 5 -extrema
Extrema = [0, 95]
Extrema = [0, 4]
$ mirtk calculate-element-wise seg95.nii.gz -extrema -mod 10.4 -extrema -mod 5 -extrema
Extrema = [0, 95]
Extrema = [0, 10.4]
Extrema = [0, 5]
mirtk calculate-element-wise seg95.nii.gz -extrema -mod 10.4 -extrema -abs -mod 5 -extrema
Extrema = [0, 95]
Extrema = [0, 10.4]
Extrema = [0, 5]
mirtk calculate-element-wise seg95.nii.gz -extrema -div 2 -mod 5 -extrema
Extrema = [0, 95]
Extrema = [0, 4.5]
mirtk calculate-element-wise seg95.nii.gz -extrema -div 2 -round -mod 5 -extrema
Extrema = [0, 95]
Extrema = [0, 4]
```
> Add -mod, -floor, -ceil, -round options to calculate-element-wise command

- Modules/IO/src/NiftiImage.cc
> Always write NIfTI ndim >= 4 such that temporal spacing is being saved

- Applications/src/evaluate-similarity.cc
The `RegisteredImage::Initialize` function must be called *after* the input source image was read, as this function determines the minimum and maximum input image intensities.
Further, as reported in #700, there is no warning/explanation for users of `evaluate-similarity` when the input images have no overlap either due to incorrect arguments or a failed registration. This change makes the program print a warning message to STDERR when either the target domain (mask) is empty, or if there is no overlap between the foreground region of the target image and the foreground region of a given source image. The program will still proceed computing the similarity measures, though, as this could potentially be handled downstream in a processing pipeline or one would not want the program to …
> fix: Initialization of transformed source image in evaluate-similarity

- Applications/src/register.cc
- Modules/Transformation/include/mirtk/JacobianConstraint.h
- Modules/Transformation/src/JacobianConstraint.cc
- Modules/Transformation/src/LogJacobianConstraint.cc
- Modules/Transformation/src/NegJacobianConstraint.cc
- Modules/Transformation/src/TopologyPreservationConstraint.cc
- Modules/Transformation/src/VolumePreservationConstraint.cc
Add options to `register` command which enable user to specify an input image with spatially varying weights for a given Jacobian determinant based penalty term.
> Spatially varying weight mask for Jacobian penalty terms

- .travis.yml
- BasisProject.cmake
- CMakeLists.txt
- Docker/Ubuntu/Dockerfile
- Dockerfile
- Documentation/install.rst
- Scripts/install_depends.sh
Update the CMakeLists.txt files to require CMake 3.4 and C++14 compiler. Use Python 3 as entrypoint of Docker image. Base Docker image on Ubuntu 18.04 (instead of 14.04). Also use Ubuntu 18.04 for Travis CI Linux tests.
> Update to Ubuntu 18.04, C++14, and CMake 3.4

- BasisProject.cmake
- Modules/Common/include/mirtk/Memory.h
Given that not many C++14 features are intended to be used just yet, C++11 is still sufficient. Also renamed recently added MakeUnique to NewUnique in alignment with NewShared and removed unnecessary overloaded versions of NewUnique and NewShared without arguments. Can't remember why this seemed necessary (maybe will fail with older compilers?!?...). Use `std::forward` to preserve move semantics when using NewUnique or NewShared helpers.
See also discussion of commit d693ef95e3d07959455cbb5ef5cc30661a57f646.
CC @jcupitt
> Revert to C++11 and provide alternative NewUnique

- .travis.yml
Otherwise AppImage requires more recent glibc and can only run on Ubuntu 18.04 or similar recent Linux distro.
> Build AppImage on Ubuntu 16.04

- .travis.yml
- Applications/src/random-dof.cc
- Scripts/install_depends.sh
- Scripts/travis.sh
Trying to run AppImage on CentOS 7 in particular. Still require CMake >=3.4, however, which is easy to install on older Linux systems. Partially reverts #707 and previous fix-up #719.
> fix: Revert to Ubuntu 14.04 for build of AppImage with older glibc and libstdc++

- .appveyor.yml
- Docker/Ubuntu/Dockerfile
The download URL for Eigen3 source release packages has changed.
> fix: Eigen3 download URL in Dockerfile and AppVeyor config

- Modules/Registration/src/NormalizedIntensityCrossCorrelation.cc
The default LNCC box window size was set to zero.
> fix: Set LNCC default box window size to 7 vox

- Applications/src/CMakeLists.txt
- Applications/src/register-points.cc
- Modules/Transformation/include/mirtk/TransformationModel.h
This command may be extended to implement other related approaches, such as robust point matching and coherent point drift if desired. For now, it mainly implements the iterative closest points (ICP) approach, where at each iteration the affine transformation which minimizes the mean squared error is fit to the residual displacements between corresponding points. This new command is related to `match-points` in that the latter implements a single iteration and produces a point correspondence map instead of a spatial transformation. Moreover, the existing `register` command could be used, but in comparison the generic registration command uses a gradient descent optimization instead of least squares fitting, and updates the point correspondences after each gradient step (i.e., more …
> enh: Add register-points command implementing ICP algorithm

- Applications/src/merge-surfaces.cc
This PR cleans the polydata of 2 surfaces (surface with intersected cells, tesselated divider polygon) that are being merged prior to merging.
If we don't do that we end up with an error in merging when iterating the points of the surfaces e.g.
```2020-10-28 12:17:34.043 (  57.500s) [        121FCE80]vtkAOSDataArrayTemplate:325    ERR| vtkFloatArray (0x55bdbe7836d0): Source array too small, requested tuple at index 168986, but there are only 168701 tuples in the array.```
This happens because the surfaces have not been properly updated.
> fix: clean surface and split polydata before merging

- Applications/src/merge-surfaces.cc
- Scripts/install_depends.sh
This PR patches change #744 to only introduce a single hole in each surface to be merged for each (largest) connected component of the label boundary. It also avoids removing cells when this would leave surface triangles that are only connected by a single vertex but not an edge.
With this PR, `mirtk recon-neonatal-cortex` should no longer produce the error:
```
Exception: Merged surface is non-closed, no. of boundaries: N
```
At the intersection where the cortical surfaces are merged.
CC @jcupitt @amakropoulos
> fix: merge-surfaces creation of small holes at label boundary

- Applications/src/CMakeLists.txt
- Applications/src/clean-surface.cc
This command can be used to fix the geometry and/or topology of a cortical surface mesh, for example.
See below an example of `-remove-spikes` for a neonatal cortical surface mesh produced by `deform-mesh` (dHCP subject CC00381XX11, session 121600). Alternatively, point merging may introduce duplicate or boundary faces in this case, when the specialized `-remove-spikes` option is not used. Here, `-merge-points` followed by `-remove-duplicates` and `-remove-boundaries` can restore the topology to a Genus 0 closed surface.
When the mesh is a closed triangular mesh, except for minor defects that may be discarded such as the spike in the below example screenshot, use `mirtk clean-surface input.vtp output.vtp -all` to apply all steps.
CC @jcupitt @amakropoulos
> enh: Add clean-surface command

- Modules/PointSet/include/mirtk/Triangle.h
- Modules/PointSet/src/Triangle.cc
This commit includes two bug fixes relating to `SurfaceCollisions` filter:
- Segmentation fault cased by [unresolved VTK issue](https://gitlab.kitware.com/vtk/vtk/-/issues/17722).
- Fix of `DistanceBetweenTriangles()` function used by `SurfaceCollisions` filter when `FastCollisionTestOff()`.
CC @amakropoulos
> fix: DistanceBetweenTriangles and TriangleTriangleIntersection

- Applications/src/evaluate-surface-mesh.cc
- Modules/PointSet/include/mirtk/SurfaceCollisions.h
- Modules/PointSet/src/SurfaceCollisions.cc
This change fixes mistakes in the `SurfaceCollisions` filter. A related issue is #753, and both should be merged together.
The projection of triangles with a shared edge to 2D in order to check if both other vertices are on the same side of this edge was implemented incorrectly. Both triangles were projected to a different 2D plane. After initially fixing this, I eventually figured to simply compute the inner product between the vectors from the edge midpoint to each of the two other triangle vertices. An angle of less than 90 degrees means that triangles are folding onto each other.
Similarly, I've added a near-miss collision check for adjacent triangles, which either share an edge or a single vertex. Previously, the `SurfaceCollisions` filter would only detect intersections in these …
> Fix and extend SurfaceCollisions filter
