BioMedIA/MIRTK

Modules/Numerics/include/mirtkPolynomial.h, Modules/Numerics/src/mirtkPolynomial.cc, Modules/Transformation/src/mirtkEnergyTerm.cc
=> Add Polynomial::EvaluateTaubinDistance, replace '.' in energy term name

Applications/convert-image.cc
Keep input voxel type when no specific output voxel type requested.
=> fix: Voxel type of convert-image output image [Applications]

Applications/extract-image-region.cc
=> enh: Add -patch and -closest-patch options to extract-image-region [Applications]

Applications/convert-pointset.cc, Modules/PointSet/src/mirtkPointSetUtils.cc
This file format is in particular used by the CGAL library.
http://segeval.cs.princeton.edu/public/off_format.html
=> Add support for Object File Format (.off)

Applications/evaluate-distance.cc
Minor enhancement of ```evaluate-distance``` output. Added missing help of command options.
=> enh: Document and add additional options to evaluate-distance [Applications]

Modules/PointSet/include/mirtkPolyDataSmoothing.h, Modules/PointSet/src/mirtkPolyDataSmoothing.cc
Other changes are related to the implicit surface distance in normal direction without (experimental) detection of outliers in the isosurface based on geometric assumptions. This code was not ready for release yet and is removed with this PR.
=> Weighted averaging of deformable surface gradient vectors

Modules/Image/src/mirtkShapeBasedInterpolateImageFunction.cc
Also, print verbose messages only when global ```verbose``` flag is set.
=> style: ShapeBasedInterpolateImageFunction nested for loops

Modules/Common/BasisProject.cmake, Modules/Common/include/mirtkString.h, Modules/Common/src/mirtkString.cc, Modules/Common/test/CMakeLists.txt, Modules/Common/test/testString.cc, Modules/Registration/src/mirtkNormalizedIntensityCrossCorrelation.cc
These auxiliary functions should make it more standardised how parameters with different possible value units are dealt with during the parsing of the configuration file.
=> Enh: Add auxiliary functions for dealing with parameter/value units

CMake/CMakeLists.txt
=> fix: Installation of CMake Modules after renaming [CMake]

.gitignore
Add ```.*.swp``` file pattern to ```.gitignore``` file.
=> enh: Add .*.swp files to .gitignore

Documentation/install.rst
=> doc: Document minimum required VS compiler version [Documentation]

Applications/calculate-distance-map.cc, Modules/Image/src/mirtkEuclideanDistanceTransform.cc
Includes also a commit with minor style/refactoring of 2D Euclidean distance map filter function.
=> Fix calculate-distance-map -3D option

ThirdParty/LBFGS/CMakeLists.txt, ThirdParty/NiftiCLib/CMakeLists.txt
A minor change that has no practical effect.
=> enh: Call CMake's project command in ThirdParty project subdirectories

Modules/Registration/src/GenericRegistrationFilter.cc
- Closes and replaces PR #79.
- Fixes also parsing of ```Edge length of surface <n>```.
=> enh: Image pyramid 'Resolution' and 'Blurring' parameter units [Registration]

Modules/IO/src/NiftiImageReader.cc
- Use NIfTI C library functions to get image and header file from given file path.
- Check header if file format is NIfTI ASCII, NIfTI-1, or NIfTI-2.
- In case of NIfTI-2, do not support reading the file if CIFTI extension is present.
- Determine whether file content has to be swapped by checking nim->byte order.
Tested by reading NIfTI-1 files from OASIS dataset and [these NIfTI-2 test images](http://nifti.nimh.nih.gov/pub/dist/data/nifti2/).
Closes #150 and #151.
=> fix: NIfTI-2 support of NiftiImageReader [IO]

Modules/IO/src/NiftiImageReader.cc
This is a fixup of PR #180 where the NIfTI header extensions were not parsed correctly. Tested the modification now on NIfTI-1, NIfTI-2, and a CIFTI file from the HCP project. In case of a CIFTI file, the ```BaseImage::New``` function raises an error with the message that the file cannot be opened as of #150.
=> fixup: Check for CIFTI extension in NIfTI-2 header [IO]

CMake/Basis/CommonTools.cmake
=> fix: Use of CMake 3 continue command [BASIS]

CMakeLists.txt.user, Modules/Common/include/mirtk/ObjectFactory.h, Modules/Numerics/include/mirtk/LocalOptimizer.h, Modules/Numerics/src/LocalOptimizer.cc, Modules/Transformation/include/mirtk/EnergyTerm.h, Modules/Transformation/src/EnergyTerm.cc
=> fix: Define singleton factory instance getter in base class .cc

Applications/tools/CMakeLists.txt, CMake/Basis/ProjectTools.cmake, CMake/Basis/UtilitiesTools.cmake
=> enh: Finalize custom targets immediately

Applications/BasisProject.cmake, Applications/src/CMakeLists.txt
TBB was missing as (optional) dependency.
=> fix: Run time reporting of register command when running multi-threaded with TBB [Applications]

Applications/src/evaluate-similarity.cc
Just a minor change that adds some verbose progress output messages.
=> enh: Add further verbose messages to evaluate-similarity command [Applications]

Modules/Common/include/mirtk/Matlab.h
=> fix: pragma GCC diagnostic unknown warning option [Common]

Applications/src/evaluate-distortion.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/236)
=> fix: Build of evaluate-distortion command with VTK 6.0 [Applications]

Applications/src/evaluate-distortion.cc
Fixup for #236... Travis CI build for PR's coming up next.
=> fixup: Build of evaluate-distortion command [Applications]

.travis.yml, README.md, Testing/Travis/before_install.sh, Testing/Travis/script.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/239)
=> enh: Add Travis CI scripts for Ubuntu 14.04 (Trusty) and OS X

Modules/Common/test/testString.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/242)
=> fix: Warnings when building testString [Common]

Applications/tools/mirtk.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/241)
=> fix: Print error message when command returned non-zero exit code [Applications]

Applications/src/evaluate-surface-overlap.cc, Modules/PointSet/src/PointLocator.cc
Closes #243.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/245)
=> fix: Unknown -Wno-unused-local-typedefs warnings [PointSet,Applications]

Applications/BasisProject.cmake, Applications/src/convert-dof.cc, BasisProject.cmake, CMakeLists.txt, CONTRIBUTING.md, ChangeLog.txt, Documentation/commands/_descriptions/convert-dof.rst, Documentation/commands/copy-pointset-attributes-from-mat.rst, Documentation/download.rst, Modules/Common/BasisProject.cmake, Modules/IO/BasisProject.cmake, Modules/Image/BasisProject.cmake, Modules/Numerics/BasisProject.cmake, Modules/PointSet/BasisProject.cmake, Modules/Registration/BasisProject.cmake, Modules/Transformation/BasisProject.cmake, Templates/mirtk-module/1.0/BasisProject.cmake
Final fixes and documentation of changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/258)
=> Release 1.1.0

Documentation/download.rst, Documentation/help.rst, Documentation/install.rst, Documentation/modules/_overview.rst, Documentation/modules/_refs.rst
Fixup for PR #266.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/267)
=> fix: Renaming of VolumetricMapping module [Documentation]

CMake/Basis/CommonTools.cmake
Fix up for #265.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/270)
=> fix: Build of Python script with future statements [BASIS]

Modules/Numerics/include/mirtk/Vector.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/274)
=> enh: Add Vector::Sum function [Numerics]

Applications/src/evaluate-dof.cc
=> fix: Use SharedPtr instead of shared_ptr [Applications]

Modules/Image/include/mirtk/Histogram1D.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/278)
=> typo in Histogram1D

Modules/Common/include/mirtk/Math.h, Modules/Common/src/Math.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/280)
=> enh: Add nan and inf constants [Common]

Applications/src/convert-pointset.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/282)
=> enh: Use convert-pointset -merge also for combined vtkPolyData [Applications]

Modules/Image/include/mirtk/HashImage.hxx
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/285)
=> fix: Unused variable warnings in HashImage [Image]

Documentation/download.rst, Documentation/install.rst, Documentation/modules.rst, Documentation/modules/_descriptions/drawem.rst, Documentation/modules/_overview.rst, Documentation/modules/_refs.rst, Documentation/modules/drawem.rst, Documentation/publications.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/288)
=> doc: Draw-EM module, download, and publication

Modules/PointSet/include/mirtk/EdgeTable.h, Modules/PointSet/src/EdgeTable.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/297)
=> enh: Add EdgeTable::MaxNumberOfAdjacentPoints [PointSet]

Modules/PointSet/include/mirtk/PointSetUtils.h, Modules/PointSet/src/PointSetUtils.cc
In particular the Cotangent function is useful for the implementations of the Mapping module.
=> enh: Add further PointSetUtils functions [PointSet]

Applications/src/evaluate-distortion.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/299)
=> enh: Refactor evaluate-distortion command and add angular distortion measure [Applications]

Applications/src/info.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/301)
=> fix: Print surface mesh info only for surface meshes [Applications]

Modules/Common/include/mirtk/Common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/302)
=> fix: Include Numerics.h in Common.h [Common]

Modules/Common/include/mirtk/Algorithm.h, Modules/Image/src/ConnectedComponents.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/303)
=> enh: Add auxiliary functions to find element in array and to reorder entries [Common,Image]

Modules/Numerics/include/mirtk/Matrix.h, Modules/Numerics/src/Matrix.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/307)
=> Minor fixes of Matrix class and Matrix::Col accessor addition

CMake/Config/Depends.cmake, Modules/Numerics/config/Settings.cmake, Modules/Numerics/src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/306)
=> fix: Build with LBFGS [Numerics]

Applications/src/delete-pointset-attributes.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/304)
=> fix: Removal of cell data arrays with delete-pointset-attributes [Applications]

CMake/Modules/FindSuiteSparse.cmake, CMake/Modules/FindUMFPACK.cmake, Documentation/install.rst, Modules/Numerics/CMakeLists.txt, Modules/Numerics/config/Settings.cmake, Modules/Numerics/src/SparseMatrix.cc
Closes #262.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/305)
=> fix: Add FindSuiteSparse.cmake module and use it to FindUMFPACK

Applications/src/combine-images.cc
Fixup for #303 which renamed `SortIndicesOfArray` functor and added `IncreasingOrder` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/310)
=> fix: Use new IncreasingOrder helper in combine-images [Applications]

Modules/Common/include/mirtk/VtkMath.h, Modules/PointSet/include/mirtk/PointSetUtils.h, Modules/PointSet/include/mirtk/Triangle.h, Modules/PointSet/src/PointSetUtils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/312)
=> enh: Point set area, edge lengths, and vtkMath 2D utility functions

Modules/Numerics/include/mirtk/PolynomialSolvers.h, Modules/Numerics/include/mirtk/Vector.h, Modules/Numerics/src/CMakeLists.txt, Modules/Numerics/src/PolynomialSolvers.cc
This solver can be used to find the roots of a 3rd degree polynomial. It is used in particular to find the extrema of a 4th degree polynomial function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/313)
=> enh: Add solver for cubic equation

Applications/src/evaluate-distortion.cc
Docker image build failed because of this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/323)
=> fix: Missing vtkPointData.h include [Applications]

Modules/Registration/src/HistogramImageSimilarity.cc
=> fix: Initialize _UseParzenWindow flag of HistogramImageSimilarity [Registration]

Modules/Common/include/mirtk/Math.h, Modules/Common/src/Math.cc, Modules/Image/include/mirtk/Histogram1D.h, Modules/Image/include/mirtk/Histogram2D.h, Modules/Image/src/Histogram1D.cc, Modules/Image/src/Histogram2D.cc, Modules/Registration/include/mirtk/HistogramImageSimilarity.h, Modules/Registration/include/mirtk/NormalizedMutualImageInformation.h, Modules/Registration/src/NormalizedMutualImageInformation.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/336)
=> enh: NMI performance

Applications/src/evaluate-cardiac-motion.cc
1. Fixed a bug. Line 118: should be v_pc = c - p.
2. Improved Line 118. Removing the longitudinal component of v_pc will lead to a more robust check of whether this vector is pointing inside the heart or outside.
3. Line 402: Added  "output_points->SetNumberOfPoints(npoints);" so that output_points is allocated before use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/341)
=> Improved code

Applications/src/calculate-element-wise.cc
Closes #343.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/344)
=> fix: Build of calculate-element-wise without VTK [Applications]

Applications/src/copy-pointset-attributes.cc
Add `-pointdata-as-celldata` and `-celldata-as-pointdata` options to copy-pointset-attributes command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/345)
=> enh: Add -pointdata-as-celldata and -celldata-as-pointdata option [Applications]

Applications/src/offset-surface.cc
Minor changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/347)
=> enh: Add -offset option to offset-surface tool, use vtkCellDataToPointData filter [Applications]

Modules/Common/include/mirtk/EnergyMeasure.h
In preparation for additional terms as part of the Deformable package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/348)
=> enh: Add enumeration entries for Gauss and mean curvature force terms [Common]

Applications/src/calculate-surface-attributes.cc, Modules/PointSet/include/mirtk/MeshSmoothing.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/349)
=> add smooth weighting options

Applications/src/info.cc, Modules/PointSet/include/mirtk/PointSetUtils.h, Modules/PointSet/src/PointSetUtils.cc, Modules/PointSet/src/SurfaceCurvature.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/350)
=> surface area information

Applications/src/project-onto-surface.cc
Allows to project scalars from another surface according to the closest points
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/351)
=> enh: project-onto-surface

Modules/IO/src/PointSetIO.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/352)
=> Allow shape gifti files

Applications/src/copy-pointset-attributes.cc
- When data array name contains the string "label" (case insensitive), majority voting is used for `-pointdata-as-celldata` and `-celldata-as-pointdata` conversion. The default is an averaging.
- When no command-line arguments given, copy all data arrays.
- Preserve individual component names when copying data arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/360)
=> fix: Various fixes of copy-pointset-attributes [Applications]

Modules/Image/include/mirtk/InterpolateImageFunction.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/361)
=> enh: Add InterpolateImageFunction overloads for Point arguments [Image]

Modules/Numerics/include/mirtk/Point.h
Fixes the build with previously committed changes that already makes use of these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/363)
=> enh: Add x, y, z member references to Point class [Numerics]

Applications/src/extract-pointset-surface.cc
Fix up for commit 22aee1c which was part of PR #339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/364)
=> fix: Segfault in extract-pointset-surface caused by -source-array change [Applications]

Applications/lib/python/mirtk/subprocess.py.in
Addition to #366.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/367)
=> enh: Add verbose argument to mirtk.run function [Applications]

Applications/lib/python/mirtk/subprocess.py.in
Addition to PR #366.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/370)
=> enh: Python run function with ordered list of options

Applications/src/convert-pointset.cc, Applications/src/copy-pointset-attributes.cc, Modules/Common/include/mirtk/String.h, Modules/Common/src/String.cc, Modules/IO/include/mirtk/PointSetIO.h, Modules/IO/src/PointSetIO.cc
Complements #355 and #358. Adds ability to read (surface) point data from CSV file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/368)
=> enh: Read point set attributes from CSV

Modules/Common/include/mirtk/Object.h
Fix for PR #356.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/372)
=> fix: Ambiguity of static/non-static Object::Throw call [Common]

Applications/src/extract-connected-components.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/374)
=> bug in LCC label output

Modules/Common/include/mirtk/Vtk.h, Modules/Common/src/Vtk.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/376)
=> enh: Optionally allocate data array in NewVtkDataArray [Common]

Applications/src/convert-dof.cc
Instead of reflecting the data of the warp, change the direction of the x axis for the image to world and vice versa transformation. The resulting warp file will always have negative determinant. Also, do the same for the source image world to image transformation! This was missing before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/375)
=> fix: Reflect x axis when converting to FSL warp [Applications]

Applications/src/project-onto-surface.cc
Will need to merge this with PR #357 as auto-merge may fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/387)
=> enh: project-onto-surface -dilation-radius option [Applications]

Modules/Common/include/mirtk/Algorithm.h, Modules/PointSet/include/mirtk/MedianMeshFilter.h, Modules/PointSet/src/CMakeLists.txt, Modules/PointSet/src/MedianMeshFilter.cc
Median filter for mesh node data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/389)
=> enh: Add MedianMeshFilter

Modules/PointSet/src/MedianMeshFilter.cc
Fix up for PR #389.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/390)
=> fix: MedianMeshFilter [PointSet]

Applications/src/project-onto-surface.cc
Resolved conflicts with current master and #357. Addressed open discussions of proposed changes by @amakropoulos. This PR therefore replaces PR #357.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/391)
=> enh: Project labels onto surface [Applications]

Modules/Common/include/mirtk/EnergyMeasure.h
Force used to refine cortical white surface, to align it with the image edges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/392)
=> enh: Deformable module with ImageEdgeDistance force

Applications/src/project-onto-surface.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/395)
=> enh: Use Array instead of std::vector, boolean options [Applications]

Applications/src/dilate-scalars.cc, Applications/src/erode-scalars.cc
Fix up for PR #388.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/396)
=> fix: Setting of point data attribute in dilate/erode-scalars [Applications]

Modules/PointSet/src/SurfaceRemeshing.cc
Another fix would have been to first call DeleteCell before ReplaceCellPoint as the later is modifying the point cells array (e.g., vtkPolyData::ResizeCellList). However, it is safer to make a copy of the IDs to avoid any more such mistakes, i.e., when implementing the cell data interpolation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/397)
=> fix: Node melting during surface remeshing [PointSet]

Modules/Common/include/mirtk/Options.h
Helps to identify which argument is incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/399)
=> enh: Report which command argument is unkown [Common]

Applications/src/merge-surfaces.cc
Fix up for #379.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/401)
=> fix: Require at least 50% of inside label to be considered [Applications]

Modules/PointSet/src/Triangle.cc
See also PR #382 and #378.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/398)
=> enh: Check bounding spheres for intersection in case of triangle intersection [PointSet]

Modules/PointSet/include/mirtk/MeshSmoothing.h, Modules/PointSet/src/MeshSmoothing.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/403)
=> enh: Add NormalDeviation MeshSmoothing weighting function [PointSet]

Applications/src/subdivide-brain-image.cc
Seems to work better than the naive approach which assumes (perfectly) symmetric RH/LH segmentations. Also, ensure there is some cortical GM between WM and cerebellum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/405)
=> fix: Use PCA to find medial cutting plane [Applications]

Applications/src/merge-surfaces.cc
Should work for more cases now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/404)
=> enh: Consider cutting plane rotations when searching for division cut [Applications]

.travis.yml, Applications/src/calculate-element-wise.cc, Scripts/install_depends.sh, Scripts/travis.sh
Closes #408.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/409)
=> fix: Build without VTK, add CI config WITH_VTK=OFF

Applications/src/merge-surfaces.cc
The edge intersection point may only be snapped to the closest edge end point, not the opposite triangle point even if within tolerance radius. Otherwise the resulting mesh with tesselated divider polygon inserted may have incorrect topology (i.e., holes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/410)
=> fix: Snapping of divider edge points to merged surface [Applications]

Applications/src/subdivide-brain-image.cc
Fix up for #405.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/412)
=> fix: Segfault in subdivide-brain-image [Applications]

Applications/src/transform-image.cc
The type of the transformed image should match the type of the untransformed image, not the type of the target image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/416)
=> fix: Type of transformed image [Applications]

Applications/src/smooth-surface.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/417)
=> fix: Output normals after smoothing of non-genus-0 surface [Applications]

Modules/Common/include/mirtk/EnergyMeasure.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/407)
=> enh: Use latest Deformable module

Applications/src/merge-surfaces.cc, Applications/src/subdivide-brain-image.cc, Modules/PointSet/include/mirtk/SurfaceRemeshing.h, Modules/PointSet/include/mirtk/Triangle.h, Modules/PointSet/src/SurfaceRemeshing.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/413)
=> fix: Intersections of divider with itself or merged surfaces [Applications]

Modules/Common/include/mirtk/String.h, Modules/Common/src/Options.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/418)
=> fix: Do not treat negative number arguments like option names

Modules/PointSet/src/PointSetUtils.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/419)
=> fix: GetMinMaxEdgeLength [PointSet]

Applications/src/merge-surfaces.cc, Modules/PointSet/src/SurfaceRemeshing.cc
Includes minor change of `SurfaceRemeshing` to avoid use of cast to convert boolean value to integer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/420)
=> fix: merge-surfaces remeshing [Applications]

Applications/src/merge-surfaces.cc
Moreover, use close to zero tolerance for merging output points such that divider and split surface are only merged at divider boundary points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/422)
=> fix: Remove divider boundary cells which result in duplicate output triangles [Applications]

Modules/PointSet/include/mirtk/EdgeTable.h, Modules/PointSet/include/mirtk/PointSetUtils.h, Modules/PointSet/src/PointSetUtils.cc
Minor additions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/423)
=> enh: Add EdgeIterator constructor, BoundaryEdges overload

Applications/src/smooth-image.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/426)
=> enh: smooth-image sigma value units ‘mm’, ‘vox’, or ‘signed’ [Applications]

Applications/config/Depends.cmake, Applications/src/CMakeLists.txt, Applications/src/extract-pointset-cells.cc, Modules/Image/include/mirtk/NearestNeighborInterpolateImageFunction.h
Add tool to extract point set / surface cells matching given cell data criteria.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/424)
=> add: extract-pointset-cells [Applications]

Applications/lib/python/mirtk/subprocess.py.in, Applications/src/CMakeLists.txt, Applications/src/blend-surface.cc, Applications/src/calculate-surface-attributes.cc, Applications/src/convert-pointset.cc, Applications/src/copy-pointset-attributes.cc, Applications/src/delete-pointset-attributes.cc, Applications/src/dilate-scalars.cc, Applications/src/erode-scalars.cc, Applications/src/extract-pointset-cells.cc, Applications/src/extract-pointset-surface.cc, Applications/src/info.cc, Applications/src/offset-surface.cc, Applications/src/project-onto-surface.cc, Applications/src/smooth-surface.cc, Applications/src/transform-points.cc, Modules/Common/include/mirtk/Algorithm.h, Modules/Common/include/mirtk/DataSelection.h, Modules/Common/include/mirtk/Vtk.h, Modules/PointSet/src/PointSetUtils.cc
A number of changes of the applications used for the cortical surface reconstruction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/430)
=> enh: Misc surface recon related applications improvements

Applications/src/delete-pointset-attributes.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/433)
=> enh: delete-pointset-attributes options accept multiple arguments [Applications]

Applications/src/merge-surfaces.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/434)
=> fix: Joining of surfaces in merge-surfaces [Applications]

Applications/src/subdivide-brain-image.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/biomedia/mirtk/435)
=> enh: Add separate subdivide-brain-image closing options [Applications]

Applications/src/subdivide-brain-image.cc
Output image used to determine approximate distance of point within cerebrum to the "cortical hull".
=> enh: Add subdivide-brain-image -output-inner-cortical-distance option [Applications]

Applications/src/calculate-distance-map.cc
=> enh: Add common options to calculate-distance-map [Applications]

Applications/src/subdivide-brain-image.cc
Add options to `subdivide-brain-image` that can be used to ensure that the resampled label image contains a given brain segmentation mask entirely.
=> enh: Add -margin and -fg mask option to subdivide-brain-image [Applications]

Modules/IO/src/gifti/gifti_xml.cc
=> fix: Missing free in gifti_xml.cc [IO]

Applications/src/close-scalars.cc, Applications/src/dilate-scalars.cc, Applications/src/erode-scalars.cc, Applications/src/open-scalars.cc, Modules/PointSet/include/mirtk/CellDataFilter.h, Modules/PointSet/include/mirtk/CloseCellData.h, Modules/PointSet/include/mirtk/DilateCellData.h, Modules/PointSet/include/mirtk/ErodeCellData.h, Modules/PointSet/include/mirtk/OpenCellData.h, Modules/PointSet/src/CMakeLists.txt, Modules/PointSet/src/CellDataFilter.cc, Modules/PointSet/src/CloseCellData.cc, Modules/PointSet/src/DilateCellData.cc, Modules/PointSet/src/ErodeCellData.cc, Modules/PointSet/src/OpenCellData.cc, Modules/PointSet/src/OpenPointData.cc
Morphological operations can now be performed on images, mesh node data, and mesh cell data.
=> enh: Enable morphological operations also on cell data [Applications]

Applications/src/merge-surfaces.cc
=> fix: Reduce min inside-label count expected by merge-surfaces [Applications]

Modules/Registration/src/GenericRegistrationFilter.cc
=> fix: Set edge length parameter to common 'Level 0' values [Registration]

Modules/PointSet/include/mirtk/PointLocator.h, Modules/PointSet/src/ClosestPoint.cc, Modules/PointSet/src/PointLocator.cc, Modules/PointSet/src/RobustClosestPoint.cc, Modules/Registration/src/PointCorrespondenceDistance.cc
=> fix: Point correspondences when point set is sub-sampled [PointSet,Registration]

Modules/PointSet/include/mirtk/SurfaceCollisions.h, Modules/PointSet/include/mirtk/SurfaceCurvature.h, Modules/PointSet/include/mirtk/SurfaceRemeshing.h, Modules/PointSet/src/SurfaceCollisions.cc, Modules/PointSet/src/SurfaceCurvature.cc, Modules/PointSet/src/SurfaceRemeshing.cc
Required for build as DLL with VC on Windows.
=> fix: DLL export of const data members [PointSet]

Applications/src/subdivide-brain-image.cc
The correction of wrongly cut WM into RH/LH hemisphere labels has been done before the resampling to standard space only. During the resampling, this correction was lost again when the resampled image was cut again with the computed medial cutting plane. This commit applies the RH/LH label correction (again) after the resampling of the label image.
=> fix: subdivide-brain-image RH/LH labels after resampling [Applications]

Applications/src/subdivide-brain-image.cc
Remove small unconnected white matter components instead of assigning them the wrong label.
=> fix: Correction of RH/LH white matter labels

Modules/Common/include/mirtk/Array.h, Modules/Common/include/mirtk/List.h, Modules/Common/include/mirtk/Memory.h, Modules/PointSet/include/mirtk/Triangle.h, Modules/PointSet/src/SurfaceCollisions.cc, Modules/PointSet/src/Triangle.cc
=> fix: Build of SurfaceCollision filter with VTK 7.1 [PointSet]

Applications/src/evaluate-overlap.cc
- Add ability to merge segments corresponding to multiple `-label` values.
- Add `-labels` option to evaluate overlap for each individual label.
=> enh: Evaluate overlap of more than one label at once, merge segments [Applications]

Applications/src/evaluate-jacobian.cc
- Fix reported min/max values.
- Use SS also when SV FFD in MFFD with one level and no global component.
- Use nullptr instead of NULL.
- Use UniquePtr for dynamically allocated objects.
=> enh/fix: Slight refactoring, add -ss [fast] option, fix min/max output [Applications]

Applications/src/average-images.cc
- Fix-up of #523 for averaging of segmentations to produce prior probability maps.
- Improves upon previous averaging with NN interpolation by first binarizing the input images and then using linear interpolation.
=> fix: Average binarized label images using linear interpolation [Applications]

Applications/src/transform-image.cc, Modules/Image/include/mirtk/HashImage.h
Smoother resampling of binary masks and segmentation images.
=> enh: Add transform-image -labels option [Applications]

Applications/src/evaluate-overlap.cc
- Allow `cout` or `stdout` as `-table` option argument and use it as default if no argument given.
- Remove extra newline from verbose output when `-table` option not given.
=> enh: evaluate-overlap -table option without argument, fix extra newline [Applications]

Applications/src/average-images.cc
A threshold on the cumulative normalized weight helps to suppress non-smooth boundaries caused by few individual misaligned images which should have little influence on the average (i.e., low weight).
=> enh: Add average-images -threshold option [Applications]

Applications/src/average-images.cc
Min/max of Laplacian filter output has to be determined within foreground only.
=> fix: average-images -sharpen with -padding [Applications]

Applications/src/evaluate-dof.cc
The `evaluate-dof -barycentric-equation` option can be used to assess the amount of residual average transformation given N affine template-to-subject registrations.
=> enh: Add evaluate-dof -barycentric-equation option [Applications]

Applications/src/init-dof.cc
`init-dof sim.dof -dofin aff.dof -similarity` can be used to restrict an affine transformation to a similarity transformation.
=> enh: Add init-dof -similarity option [Applications]

Applications/src/average-images.cc
No need to write extra file for this.
=> enh: Pass average-images weight as second -image option argument [Applications]

Applications/src/compose-dofs.cc
Related to recent change of `compose-dofs`.
=> fix: Composed SV FFD BCH parameters same as first input [Applications]

Modules/Image/src/HessianImageFilter.cc
Fixes use of NGF_COS similarity measure in registration of 2D images.
=> fix: NaN when using Hessian image filter for 2D image with dz=0 [Image]

Applications/src/average-dofs.cc
Using these new options makes it possible to avoid the initial reading of all transformations just to figure out the common type and average FFD attributes. Could also be improved by not reading the whole transformations but only the header information...
=> enh: average-dofs -type and -target 'common' to avoid reading files twice [Applications]

Applications/src/transform-image.cc
Options `-dofin` and `-dofin_i` accept multiple arguments. Same for `-label/-labels` option which also accepts `<from>..<to>` label ranges.
=> enh: transform-image multiple -dofin and -label args [Applications]

Applications/src/average-images.cc
- Change input image type to `float`.
- Allow multiple segmentation labels to be merged for generation of average probability map.
=> enh: Use float as input type of average-images, merge multiple -labels [Applications]

Modules/Registration/include/mirtk/ImageSimilarity.h
Add `Domain` image similarity foreground option. When set, the similarity is evaluated for all voxels regardless of the set foreground domain `_Mask`. Same as `register -reset-mask` together with `Mask` image similarity foreground domain, but can be set via configuration file without need for explicit `register` command option.
=> enh: Add FG_Domain option to ImageSimilarity [Registration]

Applications/src/average-overlap.py
Add `-noheader` and `-noid` column options to `average-overlap` script.
=> enh: Add average-overlap -noheader and -noid column option [Applications]

Applications/src/aggregate-images.cc
Fix of background value in output of `aggregate-images`.
=> fix: aggregate-images background value [Applications]

Applications/src/average-images.cc
Use transformation file path prefix `inv:` or `dof:` to indicate if inverse of the transformation maps from image to average space or vice versa, respectively. If no such prefix given, assume `dof:` as before this change.
=> enh: Use “inv:” prefix in average-images input text file [Applications]

.travis.yml, Applications/config/Depends.cmake, CMakeLists.txt, Modules/Common/BasisProject.cmake, Modules/IO/BasisProject.cmake, Modules/Image/BasisProject.cmake, Modules/Numerics/BasisProject.cmake, Modules/PointSet/BasisProject.cmake, Modules/Registration/BasisProject.cmake, Modules/Transformation/BasisProject.cmake, Scripts/install_depends.sh, Scripts/travis.sh
- Change CMake config to look for VTK 8, 7, and 6.
- Hopefully faster Travis CI builds for macOS using Travis CI caching of Homebrew directories and by disabling build with ARPACK (homebrew installation includes costly dependency on gcc) and UMFPACK.
=> fix: Travis CI build, support build with VTK 8

Applications/src/aggregate-images.cc, Applications/src/average-measure.py, Applications/src/evaluate-overlap.cc, Applications/src/evaluate-similarity.cc
Changes of evaluation tools used for atlas evaluation.
- `evaluate-similarity` output format options.
- `evaluate-overlap` output format options, `-prob` option for general DSC.
- `aggregate-images` normalization fix, entropy measures
- `average-measures` output standard deviation and number of samples to separate tables.
=> enh: Evaluation tools [Applications]

Applications/doc/construct-atlas-config.json, Applications/lib/python/mirtk/atlas/spatiotemporal.py, Applications/src/CMakeLists.txt, Applications/src/construct-atlas.py, Applications/src/evaluate-atlas.py
Add commands `construct-atlas` and `evaluate-atlas` used to build brain atlases using SVFFD model.
=> add: Spatio-temporal atlas construction and evaluation tools [Applications]

Modules/Registration/src/RegistrationEnergyParser.h
Users may be used to not put a space between the weight value and the energy term name/identifier. In fact there has been one such case...
Closes #495.
=> enh: Allow no space after energy term weight, e.g., 1e-3BE [Registration]

Modules/Registration/src/GenericRegistrationFilter.cc
Do not set maximum step length for affine registration based on voxel size. Moreover, do not use power of 2 to adjust step length for each resolution level as done for deformable models.
This is also similar to the IRTK `rreg2` and `areg2` commands before.
=> fix: Default ‘Maximum length of steps’ for affine registration is 1 [Registration]

Applications/src/convert-dof.cc, Modules/Transformation/src/FreeFormTransformation.cc
Convert SVFFD to NIfTI image of stationary velocity vectors and vice versa.
=> enh: Add svf_world and svf_voxel convert-dof formats [Applications]

Applications/src/combine-images.cc
=> fix: Output spacing of combine-images volume/sequence [Applications]

Applications/src/combine-images.cc
Tested with @gtarroni's cardiac stack.
```
mirtk combine-images SS_0000.nii.gz SS_0001.nii.gz -output vol_01-02.nii.gz
mirtk combine-images -input vol_01-02.nii.gz -image SS_0003.nii.gz -output vol_01-03.nii.gz
mirtk combine-images -input vol_01-03.nii.gz -image SS_0004.nii.gz -image SS_0005.nii.gz -output vol_01-05.nii.gz
```
Closes #179.
=> enh: combine-images -input option to insert/append slices to volume [Applications]

Applications/src/average-images.cc
Good to be able to use some of the functionality without actually wanting to compute an average of multiple images. Eventually, this functionality should be available as separate command.
=> enh: Allow single volume input to average-images [Applications]

Scripts/make_appimage.sh
Reference: https://travis-ci.org/AppImage/AppImageHub/builds/266225687#L541
=> Make it pass desktop-file-validate

Applications/src/convert-dof.cc
Add `-input-format elastix` option to `convert-dof`.
=> enh: Convert elastix output BSplineTransform to .dof format [Applications]

Modules/IO/src/PNGImageWriter.cc
Enable writing scalar 2D images to greyscale PNG. Not only RGB images.
=> enh: Write scalar 2D images to PNG file [IO]

CMake/Modules/FindUMFPACK.cmake
=> fix: FindUMFPACK.cmake, set UMFPACK_* vars from SuiteSparse_* [CMake]

BasisProject.cmake, ChangeLog.txt
- Set version to 2.0.0
- Add change log entry for this release.
=> Release version 2.0.0

Applications/lib/python/mirtk/batch/condor.py
Hello, I found a couple of typos in `condor.py`. It seems to be working with these fixes.
=> Missing import

Applications/lib/python/mirtk/atlas/spatiotemporal.py
@jcupitt Let me know when this fixed the issue with the atlas so we can merge it into master.
=> fix: Include discrete timepoints of final atlas in set of ages()

Applications/src/extract-image-region.cc
Also fixes parameter parsing for `-margin` and `-scale` options.
=> Add extract-image-region -margin-mm option

.gitignore, Applications/src/CMakeLists.txt, Applications/src/detect-cardiac-phases.cc
Add application from IRTK: https://github.com/BioMedIA/IRTK/blob/master/packages/cardiac/applications/cardiacphasedetection.cc 
Detect ED DS phases from cine image sets.
=> enh: add application to detect ed es cardiac phases from cine image sets

Applications/src/convert-dof.cc
Thanks, @qiuhuaqi for reporting this!
=> fix: convert-dof conversion of displacements from world to voxel units

Applications/src/CMakeLists.txt, Applications/src/auto-contrast.cc, Modules/PointSet/src/SurfaceCollisions.cc
Add application from IRTK: https://github.com/BioMedIA/IRTK/blob/master/applications/autocontrast.cc
Auto contrast an image.
=> enh: add application to create auto constrast of image

Applications/src/merge-surfaces.cc
The smoothing of interior points would then cause one of the points to be no longer at the location where it should be merged with the joined surface meshes. And without the smoothing, it would introduce an incorrect topology.
=> fix: Delete divider triangles with points all on boundary polyline in merge-surfaces

Applications/src/subdivide-brain-image.cc
Add `-fill-wm-holes` option to `subdivide-brain-image` which can be set in `recon-neonatal-cortex` configuration file (`fill_wm_holes = True`) for cases that have larger holes in between left and right hemisphere to avoid surface errors after `merge-surfaces` as in the attached screenshots.
(dHCP subjects: CC00152AN04-65700, CC00605XX11-172700, CC00605XX11-187700, CC00936XX21-11431).
=> enh: Add -fill-wm-holes option to subdivide-brain-image

CMake/Modules/mirtkAddExecutable.cmake
=> fix: Set INSTALL_RPATH executable property only when BUILD_SHARED_LIBS=ON

.vscode/launch.json, Modules/Transformation/src/MultiLevelTransformation.cc, Scripts/install_depends.sh
=> fix: MultiLevelTransformation copy constructor

CMake/Modules/FindTBB.cmake, Modules/Common/src/Parallel.cc
=> fix: Find and use newer TBB release version
